.travis.yml
Add .travis.yml file to enable CI
=> Enable travis ci build

src/Microsoft.Azure.SignalR/HubHost/ClientConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/IClientConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionContext.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/PipeReaderExtensions.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceContextFacts.cs
- Made it so tests don't depend on timeouts
- Fixed the auth bug and added unit tests
Fixes #89 
PS: I branched off the tag, but we should probably get a fix out to nuget ASAP once this is fixed.
=> Fixed auth and tests

src/Microsoft.Azure.SignalR/Utilities/AuthenticationHelper.cs
=> Make AuthenticationHelper internal

src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/MulticastDataMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
- Fix #104 
- Add test cases for `ServiceProtocol`
=> Fix MultiUserDataMessage type

build/package-test.proj, build/sources.props
Add a simple project to test restoring package from local feed.
All other things including setting up local feed is in VSTS Build
=> Add package restore tests

docs/swagger.json
=> add API descriptions in swagger

src/Microsoft.Azure.SignalR/HubHost/ServiceOptionsSetup.cs, test/Microsoft.Azure.SignalR.Tests/AddAzureSignalRFacts.cs
=> load connection string from ConnectionStrings section if default key not exist

src/Microsoft.Azure.SignalR/EndpointUtility/ServiceEndpointUtility.cs, test/Microsoft.Azure.SignalR.Tests/ConnectionStringParsingFacts.cs
=> Add Endpoint validation

build/dependencies.props
=> Update xunit related test package version

src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR/Internal/ProductInfo.cs, test/Microsoft.Azure.SignalR.Tests/ProductInfoFacts.cs
sample UA: Microsoft.Azure.SignalR/1.0.0-preview1-t000 (.NET Core 4.6.26426.02; Microsoft Windows 10.0.17134; X64)
=> Add custom UserAgent for general telemetry tracking

src/Microsoft.Azure.SignalR/HubHost/IServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestServiceConnectionManager.cs, test/Microsoft.Azure.SignalR.Tests/ServiceLifetimeManagerFacts.cs
Part of the fix to #87 
cc: @vwxyzh
=> send group message from a fixed service message

src/Microsoft.Azure.SignalR/EndpointUtility/DefaultServiceEndpointGenerator.cs, src/Microsoft.Azure.SignalR/EndpointUtility/IServiceEndpointGenerator.cs, src/Microsoft.Azure.SignalR/EndpointUtility/PreviewServiceEndpointGenerator.cs, src/Microsoft.Azure.SignalR/EndpointUtility/ServiceEndpointUtility.cs, test/Microsoft.Azure.SignalR.Tests/ConnectionStringParsingFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceEndpointUtilityFacts.cs
=> support version in connection string.

src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocolConstants.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/HubHost/IServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionContext.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/NegotiateHandler.cs, src/Microsoft.Azure.SignalR/ServiceRouteBuilder.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestServiceConnectionManager.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceContextFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceLifetimeManagerFacts.cs
This PR is part of the fix to #140 .
=> Send UpdateConnectionMessage when there is custom IUserIdProvider

src/Microsoft.Azure.SignalR.AspNet/Hubs/ServiceHubDispatcher.cs
1. `ProtocolVersion` up to 2.0
2. Use `RedirectUrl` instead of already in-use `Url`
=> [ASP.NET SignalR Service]Update the negotiate response

src/Microsoft.Azure.SignalR.AspNet/Hubs/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR.AspNet/Infrastructure/ClientConnectionManager.cs, src/Microsoft.Azure.SignalR.AspNet/Infrastructure/IClientConnectionManager.cs, src/Microsoft.Azure.SignalR.AspNet/Infrastructure/ServiceConnection.cs, src/Microsoft.Azure.SignalR.AspNet/Infrastructure/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs, src/Microsoft.Azure.SignalR.AspNet/TraceManagerLoggerProvider.cs, src/Microsoft.Azure.SignalR.Common/Constants.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ClientConnectionManagerTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs
1. Add application name to the public API
2. add comments
3. add an app connection to the service connection
4. add logger factory
=> Add application name to the public API

src/Microsoft.Azure.SignalR.AspNet/Hubs/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs
Fix https://github.com/Azure/azure-signalr/issues/203
cc @anurse
=> Fix null issue when userid is null

samples/ChatSample/Hub/Chat.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionContext.cs
=> Add client IP address in Context.HttpContext

README.md
Sounds unnecessary to expose MyGet feeds to end users
=> Remove myget source from readme

README.md
[Rendered view](https://github.com/vicancy/azure-signalr/blob/doc/README.md)
=> Update Readme to include AspNet SignalR support

README.md
=> Update readme.md to include preview version

src/Microsoft.Azure.SignalR/NegotiateHandler.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs
Fix https://github.com/Azure/azure-signalr/issues/235
=> Fix access token not included bug

src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs
For https://github.com/Azure/azure-signalr/issues/269
=> Update method remarks for more connection string hints

src/Microsoft.Azure.SignalR.Common/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs
We will send more thing in ping message.
App servers will send following information:
* how many clients connected in this hub.
* how many clients connection over this service connection.
And services also send following information to app server (not included in this PR):
* how many service instances.
* are the service connections unbalance?
* service scale information.
=> add more messages in ping.

src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs
Fix core not well handle close when loop break in ProcessOutgoingMessagesAsync().
=> Handle close when loop break in ProcessOutgoingMessageAsync

src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
* Use array instead of dictionary.
* Smaller message pack size.
=> use a compact format in ping message.

src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionManager.cs
=> fix index out of range exception when service connection is not connected.

src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs
Fix the same spelling mistake in several locations
=> Replace "incensitive" with "insensitive"

AzureSignalR.sln, test/Microsoft.Azure.SignalR.TestUtility/Microsoft.Azure.SignalR.TestUtility.csproj
Add test utility project, reused code for unit test projects can be put here
=> Add test utility project

src/Microsoft.Azure.SignalR.AspNet/TraceManagerLoggerProvider.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/Infrastructure/TestServiceMessageHandler.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TraceManagerLoggerProviderTest.cs
…ternalTraceSourceLogger instead
=> Fix stack empty exception with an InternalTraceSourceLogger instead of the TraceSourceLogger

src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs
if connection string contains "Port=xxx", then add port to request url for local test
=> add port in rest api mode

docs/rest-api.md
Update REST API doc to make it more clear about how to implement a negotiate endpoint
=> Update REST API doc

docs/tsg.md
=> Fix typo for 401 UNAUTHORIZED

docs/performance-guide.md
The updates include:
1. add more explanations for performance factors
2. highlight the process about how to evaluate performance
3. add server-less mode
=> polish perf doc

build/dependencies.props, test/Microsoft.Azure.SignalR.Management.Tests/Microsoft.Azure.SignalR.Management.Tests.csproj
Fix Management E2E UT after upgrade to core 3.0
=> Fix management e2e UT

src/Microsoft.Azure.SignalR.AspNet/DispatcherHelper.cs, src/Microsoft.Azure.SignalR.AspNet/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/IServiceConnectionManager.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/MultiEndpointServiceConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnectionContainerFactory.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceMessageBusTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestServiceConnectionContainerFactory.cs
=> [Refactor Part1] Use IServiceConnectionContainerFactory instead

NuGet.config, build/dependencies.props, build/sources.props, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, test/Microsoft.Azure.SignalR.AspNet.Tests/Microsoft.Azure.SignalR.AspNet.Tests.csproj, test/Microsoft.Azure.SignalR.Management.Tests/Microsoft.Azure.SignalR.Management.Tests.csproj, test/Microsoft.Azure.SignalR.Tests.Common/Microsoft.Azure.SignalR.Tests.Common.csproj, test/Microsoft.Azure.SignalR.Tests/Microsoft.Azure.SignalR.Tests.csproj
use `AzureSignalRSDKE2ETest` to control whether build from source code or myget package.
=> conditional build for e2e test 

src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceEndpointFacts.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs
Improve ServiceEndpoint's equality logic and improve log
=> Improve log

docs/build-source.md, run.ps1, run.sh, src/Microsoft.Azure.SignalR/HubHost/ServiceHubConnectionContext.cs, test/Microsoft.Azure.SignalR.Tests/AzureSignalRMarkerServiceFact.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/DefaultHubProtocolResolver.cs
=> Fix AspNetCore preview7 break changes

build/dependencies.props, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, version.props
* fix management std2 version bug
* remove version to version.prop
=> Releasing Microsoft.Azure.SignalR.Management v1.0.0

docs/tsg.md, test/Microsoft.Azure.SignalR.E2ETests/SignalR/TestHub.cs, test/Microsoft.Azure.SignalR.Tests.Common/E2ETest/ServiceE2EFactsBase.cs
Add a E2E test case for issue #623
=> add e2e test get remote ip

docs/tsg.md, docs/use-signalr-service.md, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/StrongServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/ServicePingMessageExtension.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnectionContext.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceContextFacts.cs, version.props
Bug Fixes:
1. Fix #623: Improve the robustness of X-Forwarded-For (#626)
2. Fix  #416, #539: Handle InstanceOfflinePing and close related clients (#612)
=> Release 1.0.12

build/dependencies.props, src/Microsoft.Azure.SignalR.AspNet/Microsoft.Azure.SignalR.AspNet.csproj, src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs, src/Microsoft.Azure.SignalR.AspNet/TraceManagerLoggerProvider.cs
=> Add EventSource provider to default logger factory

docs/tsg.md
We changed the strategy of session sticky to not rely on client request.
=> Remove the out-of-date 404 cases

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Utilities/AuthenticationHelper.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/AuthenticationHelperTest.cs, test/Microsoft.Azure.SignalR.Tests/JwtTokenHelper.cs, test/Microsoft.Azure.SignalR.Tests/ServiceEndpointProviderFacts.cs
Sticky session does not depend on signature anymore
=> Clean up claims

src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/Exceptions/ServiceConnectionNotActiveException.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnection.cs
to remove most dependencies of the semaphore lock
=> Improve ServiceConnectionBase logic 

version.props
There are dependency changes to the SDK, so update the minor version
=> Update version to 1.2.0

samples/ChatSample/ChatSample/Hub/BenchHub.cs, samples/ChatSample/ChatSample/Hub/Chat.cs, samples/ChatSample/ChatSample/Startup.cs, samples/ChatSample/ChatSample/appsettings.json
1. `dotnet run` under the ChatSample 
2. `dotnet tool install --global Microsoft.dotnet-signalr-benchmark --version 1.0.0-preview2.19521.1`
3. `dotnet signalr-bench controller -u 1 -w http://localhost:5050/bench`
Details about the benchmark tool: https://github.com/Azure/azure-signalr-bench
=> Integrate sample with benchmark tool

src/Microsoft.Azure.SignalR/ServiceRouteBuilder.cs
Disable it as well since the feature isn't ready.
Related to #689
=> Make shutdown for different Hubs run concurrently

src/Microsoft.Azure.SignalR.AspNet/DispatcherHelper.cs, src/Microsoft.Azure.SignalR.AspNet/Microsoft.Azure.SignalR.AspNet.csproj, src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs
Fix https://github.com/Azure/azure-signalr/issues/740
=> Fix runtime method not found

src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs
Add a cts to be able to cancel the application task if the user's application code is an endless one
=> Add a cts to be able to cancel the application task

src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ConnectionMigrationFeature.cs, src/Microsoft.Azure.SignalR/ServerConnections/IConnectionMigrationFeature.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceContextFacts.cs
Follow the previous discussion in #780
=> Add migration feature interfaces.

src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ConnectionMigrationFeature.cs, src/Microsoft.Azure.SignalR/ServerConnections/IConnectionMigrationFeature.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs
Minor fix namings and add missing copyrights
=> [Part2.1][Live-scale] Renamings

build/dependencies.props, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs, src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceContextFacts.cs
=> Fix client request culture

docs/rest-api.md, docs/swagger/v1.json
Update rest-api v1 swagger and md to include 
* sent to connection
* add connection
* remove connection
* close connection
* health api
Also add response code description for check customer existence and health api.
=> Update rest-api doc.

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs
=> Fix log for rebalance connection failure

src/Microsoft.Azure.SignalR.Common/Endpoints/HubServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/WeakServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceConnectionContainerBaseTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/WeakServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs
minor refactor to safely update container in scale cases.
=> Move container into HubServiceEndpoint

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, src/Microsoft.Azure.SignalR.Common/AccessTokenAlgorithm.cs, src/Microsoft.Azure.SignalR.Common/Utilities/AuthenticationHelper.cs, src/Microsoft.Azure.SignalR.Management/RestApiAccessTokenGenerator.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/AuthenticationHelperTest.cs, test/Microsoft.Azure.SignalR.Tests/ServiceEndpointProviderFacts.cs
=> Support ServiceOption to specify SecurityAlgorithm

src/Microsoft.Azure.SignalR/EndpointProvider/DefaultServiceEndpointGenerator.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs
Just found this param is not being used anymore.
=> Remove accessKey field from generator constructor

docs/use-signalr-service.md
Add `ApplicationName` explanation to doc.
Fix https://github.com/Azure/azure-signalr/issues/825
=> Update ApplicationName into options

samples/ChatSample/ChatSample.NetCore21/Dockerfile, samples/ChatSample/ChatSample/Dockerfile, samples/ChatSample/ChatSample/Hub/BenchHub.cs, samples/ChatSample/ChatSample/Hub/Chat.cs, samples/ChatSample/ChatSample/Startup.cs
1. Update `Dockerfile`
2. Add `BenchHub` to `ChatSample` for **.net3**
=> update ChatSample for .net3 and .net21

version.props
=> Change minor version

docs/use-signalr-service.md, src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs, src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ClaimsUtility.cs, src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, src/Microsoft.Azure.SignalR/ServiceOptionsExtensions.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs
=> [MaxPollInterval] Rename and document

.github/workflows/osx.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
=> only CI on neccessory files

src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/GroupMessage.cs, src/Microsoft.Azure.SignalR.Protocols/IMessageWithTracingId.cs, src/Microsoft.Azure.SignalR.Protocols/MulticastDataMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
- change tracing id protocol: 
- string -> long: 
- save space
- index is enough
=> Change tracing id protocol 

src/Microsoft.Azure.SignalR.AspNet/DispatcherHelper.cs, src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointManager.cs, src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointManager.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceEndpointProviderFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceHubDispatcherTests.cs
add IServerNameProvider dependency
=> add IServerNameProvider dependency

src/Microsoft.Azure.SignalR.Common/ServiceMessages/IMessageWithTracingIdExtensions.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/MessageWithTracingIdHelper.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceMessageTracingIdTests.cs
- Generate message tracing id, prepare for message log
=> Generate message tracing id

src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs
=> apply message tracing to service message

src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs, test/Microsoft.Azure.SignalR.Tests/Logging/MessageLogTests.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs
- add message log when the service message is from server to service
- add UT
=> add message log when the direction of service message is from server to service

test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs
=> fix e2e test.

run.ps1, run.sh, test/Microsoft.Azure.SignalR.Common.Tests/BackOffPolicyFacts.cs
Upgrade build dotnet core sdk version to latest release 3.1.401.
=> Upgrade core version to latest release 3.1.401

AzureSignalR.sln, build/dependencies.props, emulator/Microsoft.Azure.SignalR.Emulator/AppBuilderExtensions.cs, emulator/Microsoft.Azure.SignalR.Emulator/Common/JsonObjectConverter.cs, emulator/Microsoft.Azure.SignalR.Emulator/Common/PayloadMessage.cs, emulator/Microsoft.Azure.SignalR.Emulator/Common/SignalRServiceWebApiDefinition.cs, emulator/Microsoft.Azure.SignalR.Emulator/Controllers/SignalRServiceEmulatorWebApi.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/CachedHubLifetimeManager.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/DynamicConnectionHandler.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/DynamicHubContext.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/DynamicHubContextStore.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/GroupManager.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/IHubLifetimeManager.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/LeaseForArray.cs, emulator/Microsoft.Azure.SignalR.Emulator/HubEmulator/ManyToManyMap.cs, emulator/Microsoft.Azure.SignalR.Emulator/Microsoft.Azure.SignalR.Emulator.csproj, emulator/Microsoft.Azure.SignalR.Emulator/Program.cs, emulator/Microsoft.Azure.SignalR.Emulator/Properties/launchSettings.json, emulator/Microsoft.Azure.SignalR.Emulator/Startup.cs, emulator/Microsoft.Azure.SignalR.Emulator/appsettings.Development.json, emulator/Microsoft.Azure.SignalR.Emulator/appsettings.json
An initial version of emulator https://github.com/Azure/azure-signalr/issues/969
1. Support Transient mode of Serverless=>client side traffic
2. Persistent mode, Upstream are not yet supported
=> initial working version for emulator

test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs
- guid user/group name to avoid name duplicatation
=> improve management e2e tests

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs
1. ServerConnectionCount = 0 is allowed when configure the options, however it meets `DevidedByZeroException` in the container. Fix the issue.
2. Also for service ping message there is no need to report the expections if any.
=> Allow 0 server connection input and swallow ping write error

src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj
=> add deps to management

src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs
=> unready, make internal

docs/diagnostic-logs.md
=> readme prepare for portal

samples/ChatSample/ChatSample.NetCore21/package.json
=> Fix bl dependabot alert

src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs
* writing directly to local connection doesn't log
=> fix for writing directly to local connection

src/Microsoft.Azure.SignalR.AspNet/DispatcherHelper.cs, src/Microsoft.Azure.SignalR.AspNet/HubHost/ServiceMessageBus.cs, src/Microsoft.Azure.SignalR.AspNet/HubHost/SignalRMessageParser.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/Logging/AzureSignalRLog.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceMessageBusTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/SignalRMessageParserTest.cs
- message arrive server from diagnostic client
- message send to service from server
=> add message log to asp.net

Directory.Build.props, build/dependencies.props, src/Microsoft.Azure.SignalR.Emulator/Microsoft.Azure.SignalR.Emulator.csproj, src/Microsoft.Azure.SignalR.Emulator/Program.cs, src/Microsoft.Azure.SignalR.Emulator/Properties/launchSettings.json, src/Microsoft.Azure.SignalR.Emulator/Startup.cs, src/Microsoft.Azure.SignalR.Emulator/Upstreams/UpstreamOptions.cs, src/Microsoft.Azure.SignalR.Emulator/Upstreams/UpstreamOptionsExtension.cs, src/Microsoft.Azure.SignalR.Emulator/Upstreams/UpstreamTemplateItem.cs, src/Microsoft.Azure.SignalR.Emulator/appsettings.json
Usage: asrs-emulator [options] [command]
Options:
-?|-h|--help Show help information
Commands:
start To start the emulator.
upstream To init/list/update the upstream options
=> Emulator works with upstream hotload

client-generation.ps1
- delete old generated directory every time before generation
- delete useless file after generation
=> auto delete files in client generation script

samples/AspNet.ChatSample/AspNet.ChatSample.SelfHostServer/ChatHub.cs, samples/ChatSample/ChatSample.NetCore21/Hub/BenchHub.cs, samples/ChatSample/ChatSample.NetCore21/Hub/Chat.cs, samples/ChatSample/ChatSample/Hub/BenchHub.cs, samples/ChatSample/ChatSample/Hub/Chat.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/ChatHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/EndlessConnectHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/EndlessInvokeHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/ErrorConnectHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/ErrorDisconnectHub.cs
=> Minor fix for echo method

src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs
=> re-enable message log

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs
=> throw exception with unexpected ack status

src/Microsoft.Azure.SignalR.AspNet/HubHost/ServiceMessageBus.cs
1.  non-HubMessage doesn't get log when is succeeded to sent.
=> fix aspnet log

src/Microsoft.Azure.SignalR.Common/Auth/IAadAuthOptions.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerOptions.cs, test/Microsoft.Azure.SignalR.Management.Tests/RestApiProviderFacts.cs
=> Support management sdk call rest apis via AAD Token

src/Microsoft.Azure.SignalR.AspNet/Microsoft.Azure.SignalR.AspNet.csproj, src/Microsoft.Azure.SignalR.Management/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj
=> Add Package References

src/Microsoft.Azure.SignalR.Emulator/Program.cs, src/Microsoft.Azure.SignalR.Emulator/Startup.cs
Addresses https://github.com/Azure/azure-signalr/issues/969#issuecomment-716788379
=> For emulator to listenAnyIp instead

docs/tsg.md
=> Update trace config for ASPNET to add DateTime

src/Microsoft.Azure.SignalR.Management/ServiceManagerOptions.cs
=> Relesae1.6.0

version.props
=> Update version to 1.6.1 for dev

docs/sharding.md
=> Add doc about EndpointMetrics and dynamic scale.

src/Microsoft.Azure.SignalR/EndpointProvider/DefaultServiceEndpointGenerator.cs
=> Fix clientEndpoint issue for server connection

src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs
=> make validation function in ServiceManagerOptions internal

src/Microsoft.Azure.SignalR.Common/Utilities/IServiceCollectionExtension.cs, src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs
function extension will need `services.SetupOptions<>` method.
=> refactor  options set up method

build/dependencies.props, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj
=> remove unused dependency in management SDK

src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/IHasProtocol.cs, src/Microsoft.Azure.SignalR.Protocols/IHasTtl.cs, src/Microsoft.Azure.SignalR.Protocols/IMessageWithTracingId.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
add protocol field in OpenConnectionMessage.
=> add protocol in OpenConnectionMessage.

src/Microsoft.Azure.SignalR.Common/Logging/MessageLog.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs, src/Microsoft.Azure.SignalR/Internals/DefaultHubMessageSerializer.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs
reduce the message size for sending to a certain client connection by removing useless bytes for other protocol.
=> remove useless protocol serialization for a certain connection.

src/Microsoft.Azure.SignalR.Common/Auth/AadApplicationOptions.cs, src/Microsoft.Azure.SignalR.Common/Auth/AadManagedIdentityOptions.cs, src/Microsoft.Azure.SignalR.Common/Auth/AuthOptions.cs
=> make option classes internal

src/Microsoft.Azure.SignalR.Emulator/HubEmulator/HttpServerlessMessageHandler.cs, src/Microsoft.Azure.SignalR.Emulator/HubEmulator/LimitedStream.cs
Fix https://github.com/Azure/azure-signalr/issues/1152
=> Fix upstream response and add size check

src/Microsoft.Azure.SignalR.Management/IServiceContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceContext.cs
Allow user to define router externally later
=> Expose service endpoints in management SDK

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs
=> Minor fix to AddEndpointsToNegotiationStore 

src/Microsoft.Azure.SignalR.Management/Configuration/CascadeServiceOptionsSetup.cs, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptionsSetup.cs, src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/MultiEndpointConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, src/Microsoft.Azure.SignalR.Management/ManagementConnectionFactory.cs, src/Microsoft.Azure.SignalR.Management/Obsolete/ServiceManager.cs, src/Microsoft.Azure.SignalR.Management/Obsolete/ServiceManagerBuilder.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/NegotiateProcessorE2EFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/DependencyInjectionExtensionFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceContextFacts.cs
* replace Context Options with ServiceManagerOptions
* Enable service manager to create hub context for multiple endpoints
=> Move multiple endpoints support to service manager

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerBuilder.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/NegotiateProcessorE2EFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs
To get the service provider in function binding
=> Create service manager from service provder instead of new

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/MultiEndpointConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs
=> Refactor create service hub context method

src/Microsoft.Azure.SignalR.AspNet/DispatcherHelper.cs, src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointManager.cs, src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AccessKeySynchronizer.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/IAccessKeySynchronizer.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointManager.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AccessKeyTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/Endpoints/AccessKeySynchronizerFacts.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestAccessKeySynchronizer.cs, test/Microsoft.Azure.SignalR.Tests/ServiceEndpointProviderFacts.cs
=> Access key synchronizer

src/Microsoft.Azure.SignalR.Emulator/Common/SignalRServiceWebApiDefinition.cs, src/Microsoft.Azure.SignalR.Emulator/Controllers/SignalRServiceEmulatorWebApi.cs, src/Microsoft.Azure.SignalR.Emulator/HubEmulator/GroupManager.cs, src/Microsoft.Azure.SignalR.Emulator/HubEmulator/ManyToManyMap.cs
Fix https://github.com/Azure/azure-signalr/issues/1161
=> Fix emulator to be consistent with API Definition

src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs
=> fix handshake bug

src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocolConstants.cs, src/Microsoft.Azure.SignalR.Protocols/enums.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
Allow service send some warning messages back to hub server, for example:
* there is no connection with a certain certain id.
* there is no client for a certain user.
* there is no client in a certain group.
=> add service event message in service protocol.

src/Microsoft.Azure.SignalR.AspNet/DispatcherHelper.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnectionFactory.cs, src/Microsoft.Azure.SignalR.Common/DefaultServiceEventHandler.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceEventHandler.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnectionFactory.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.IntegrationTests/Infrastructure/MockServiceConnectionFactory.cs, test/Microsoft.Azure.SignalR.IntegrationTests/Infrastructure/MockServiceHubDispatcher.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceHubDispatcherTests.cs
* Add interface: `IServiceEventHandler`
* Add default implement `DefaultServiceEventHandler` by logging information.
* DI
* Update unit tests.
=> add service event handler.

src/Microsoft.Azure.SignalR.Management/IInternalServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/NegotiateProcessor.cs, src/Microsoft.Azure.SignalR.Management/NegotiationOptions.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, test/Microsoft.Azure.SignalR.Management.Tests/NegotiateProcessorFacts.cs
Ensure test cover negotation options in null
=> Use a negotiation options to wrap all the parameter

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceHubContextFacts.cs
prepare to use `ServiceHubContext` as a public abstract class.
=> Rename ServiceHubContext to ServiceHubContextImpl

src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs
=> Refactor ServiceHubContext creation in ManagementSDK

build/sources.props
=> Remove deleted nuget source

src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs
=> Allow service hub context builder to build multiple times

src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs
=> Expose multi-endpoint in Management SDK

src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs
=> Revert "Expose multi-endpoint in Management SDK (#1244)"

src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs
=> Revert "Expose multi-endpoint in Management SDK

src/Microsoft.Azure.SignalR.Common/Logging/MessageLog.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs, src/Microsoft.Azure.SignalR/ServerConnections/IServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnectionManager.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestServiceConnectionManager.cs, test/Microsoft.Azure.SignalR.Tests/ServiceHubDispatcherTests.cs
**Seems that the API is not implemented in the server side, still need to confirm.**
=> implement check if user in group for management SDK in persistent mode

samples/ChatSample/ChatSample.NetCore31/Hub/Chat.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/IConnectionStatFeature.cs
Add `IConnectionStatFeature` in sdk.
It provides following information:
- The time of client connection connected.
- The time of last message received (include ping).
- The total size of this connection received for server.
=> add connection stat.

src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs
=> Implement `SendAllExcept` and `SendToGroupExcept` for transient mode

src/Microsoft.Azure.SignalR.Protocols/CheckWithAckMessage.cs, src/Microsoft.Azure.SignalR.Protocols/GroupMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocolConstants.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
`CheckConnectionExistenceWithAckMessage` for [Check if the connection with the given connectionId exists
](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#get-check-if-the-connection-with-the-given-connectionid-exists)
`CheckAnyConnectionInGroupWithAckMessage` for [Check if there are any client connections inside the given group
](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#get-check-if-there-are-any-client-connections-inside-the-given-group)
`CheckAnyConnectionInUserWithAckMessage` for [Check if there are any client connections connected for the given user
](https://github.com/Azure/azure-signalr/blob/dev/docs/swagger/v1.md#get-check-if-there-are-any-client-connections-connected-for-the-given-user)
=> add service messages

samples/ChatSample/ChatSample.NetCore31/Hub/Chat.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs, src/Microsoft.Azure.SignalR.Protocols/CheckWithAckMessage.cs, src/Microsoft.Azure.SignalR.Protocols/GroupMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocolConstants.cs, src/Microsoft.Azure.SignalR.Protocols/enums.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/IConnectionStatFeature.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs, version.props
1. add connection stat. (#1280)
2. Improve connection drop logs (#1277)
3. Implement SendAllExcept and SendToGroupExcept for transient mode (#1287)
4. add service messages (#1286)
5. add new service events: BufferFull (#1274) …
=> Release 1.8.2

src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
=> Fix incorrect array size header for ServiceEventMessage

src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
1. add new service events: BufferFull (#1274) 
2. add service messages (#1286)
3. Implement SendAllExcept and SendToGroupExcept for transient mode (#1287)
4. Improve connection drop logs (#1277)
5. add connection stat. (#1280)
=> Release 1.8.2 

src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs
=> Fix return null for virtual async method

test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
=> improve test for user join group with ack message

src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
=> add tracing id for open/close connection message

src/Microsoft.Azure.SignalR.Common/Utilities/HttpClientFactory.cs, src/Microsoft.Azure.SignalR.Common/Utilities/RestClient.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs
- Refactor `RestClient` for unit test
=> Refactor `RestClient` for unit test

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AccessKey.cs, src/Microsoft.Azure.SignalR.Common/Utilities/RestApiAccessTokenGenerator.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs
=> add Async postfixes.

src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs
Generate message tracing id when EnableMessageTracing  is true
=> add EnableMessageTracing to ServiceManagerOptions 

src/Microsoft.Azure.SignalR.Common/ServiceMessages/IMessageWithTracingIdExtensions.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/MessageWithTracingIdHelper.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceMessageTracingIdTests.cs
update message tracing id generator: keep consistent to RT
=> update message tracing id generator: keep consistent to RT

docs/management-sdk-guide.md, src/Microsoft.Azure.SignalR.Common/ServiceMessages/IMessageWithTracingIdExtensions.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/MessageWithTracingIdHelper.cs, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceMessageTracingIdTests.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs, version.props
1. Server connection does not block on client connection lifetime (#1332)
=> Release 1.9.1

src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs
=> apply AppendMessageTracingId to persistent mode

src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs
Fix https://github.com/Azure/azure-signalr/issues/1346
=> Fix #1346 that only log warning when transport layer completes

src/Microsoft.Azure.SignalR.Management/Serialization/NewtonsoftServiceHubProtocolOptions.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerBuilder.cs
=> Make `ServiceManagerBuilder.WithNewtonsoftJson` public

version.props
=> Update version.props for 1.9.3

src/Microsoft.Azure.SignalR.Management/ServiceManagerImpl.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs
=> Set the default connection count to 3 for Mgm SDK

src/Microsoft.Azure.SignalR/ServiceOptions.cs
=> Make TransportTypeDetector internal

test/Microsoft.Azure.SignalR.Tests/ServiceMessageTests.cs
=> refactor test cases

src/Microsoft.Azure.SignalR.Common/Endpoints/HubServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, test/Microsoft.Azure.SignalR.Common.Tests/Endpoints/AccessKeySynchronizerFacts.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceConnectionContainerBaseTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/WeakServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestHubServiceEndpoint.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceEndpoint.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceEndpointProvider.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceMessageTests.cs
=> remove test codes

src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerBuilder.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerImpl.cs
* Make `ServiceManager` abstract class public
=> Make new Management SDK API public

test/Microsoft.Azure.SignalR.Common.Tests/ConnectionStringParserFacts.cs
=> connection string parser tests

src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/HealthCheckOptions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/RestHealthCheckService.cs, test/Microsoft.Azure.SignalR.Management.Tests/RestHealthCheckServiceFacts.cs
Once every 10 seconds is a little annoying
=> Extend Management rest health check interval

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, src/Microsoft.Azure.SignalR/EndpointProvider/DefaultServiceEndpointGenerator.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceEndpointFacts.cs
=> Add client/server endpoint property to `ServiceEndpoint`

src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/RestHealthCheckService.cs
One exception: when `IOptions<HealthCheckOptions>` is not null, enable it. This is used for test.
=> Disable Serverless SDK Rest health check service for single endpoint

src/Microsoft.Azure.SignalR.Management/ServiceManagerImpl.cs
=> Fix a bug in `ServiceManagerImpl.IsServiceHealthy`

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ParsedConnectionString.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AadAccessKeyTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AuthUtilityTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AzureActiveDirectoryTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/ConnectionStringParserTests.cs
=> add connection string parse result class

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl`T.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext`T.cs, test/Microsoft.Azure.SignalR.Management.Tests/StronglyTypedServiceHubContextFacts.cs
- implements IDisposable, IAsyncDisable
- Add unit tests
=> Improve strongly typed hub context

test/Microsoft.Azure.SignalR.Tests/ServiceMessageTests.cs
=> Fix testcase

build/dependencies.props, build/microbuild.proj, src/Directory.Build.props
- Use new sign mechanism (Enable it with build property "SignType=real" or "SignType=test")
=> Use new sign mechanism 

src/Microsoft.Azure.SignalR.Common/Logging/MessageLog.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, test/Microsoft.Azure.SignalR.Management.Tests/IInternalServiceHubContextFacts.cs
apply #1464 to other user group management messages
=> apply ackable message to user-group management messages in persistent mode for management sdk

build/dependencies.props, src/Microsoft.Azure.SignalR.Common/Utilities/PayloadMessageHttpContent.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ReusableUtf8JsonWriter.cs, test/Microsoft.Azure.SignalR.Common.Tests/Microsoft.Azure.SignalR.Common.Tests.csproj, test/Microsoft.Azure.SignalR.Common.Tests/Utils/PayloadMessageContentTest.cs
- Copy `ReusableUtf8JsonWriter` here
- Prepare to serialize payload with `ObjectSerializer`
=> Prepare to serialize payload with `ObjectSerializer`

src/Microsoft.Azure.SignalR.Common/Utilities/RestClient.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ReusableUtf8JsonWriter.cs, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, src/Microsoft.Azure.SignalR.Management/Serialization/IRestHubProtocol.cs, src/Microsoft.Azure.SignalR.Management/Serialization/NewtonsoftRestHubProtocol.cs, src/Microsoft.Azure.SignalR.Management/Serialization/SerializationDependencyInjectionExtensions.cs, test/Microsoft.Azure.SignalR.Management.Tests/Microsoft.Azure.SignalR.Management.Tests.csproj, test/Microsoft.Azure.SignalR.Management.Tests/RestApiProviderFacts.cs, version.props
Exposing `ObjectSerializer` will be in the later PR.
=> Apply `ObjectSerializer` to `RestClient`

src/Common/SystemTextJsonExtensions.cs, src/Common/TextMessageFormatter.cs, src/Common/TextMessageParser.cs, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, src/Microsoft.Azure.SignalR.Management/Serialization/JsonObjectSerializerHubProtocol.cs, test/Microsoft.Azure.SignalR.Management.Tests/Microsoft.Azure.SignalR.Management.Tests.csproj, test/Microsoft.Azure.SignalR.Management.Tests/Serialization/JsonObjectSerializerHubProtocolFacts.cs
- Copy files from ASP.NET Core repo here
- Add SignalR hub protocol using `ObjectSerializer`
=> Add SignalR hub protocol using `ObjectSerializer`

version.props
Dependencies have already been changed in #1520
=> Upgrade version to 1.15.0

version.props
Reverts Azure/azure-signalr#1547
=> Revert "update version to release"

src/Microsoft.Azure.SignalR.Common/Utilities/RestClient.cs, test/Microsoft.Azure.SignalR.Common.Tests/RestClients/RestClientFacts.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestRootHandler.cs
=> `RestClient` Set StatusCode on `HttpRequestException` on .NET 5 or greater

version.props
Plan to add new features soon. So update the minor version.
=> Update version to 1.16.0

src/Microsoft.Azure.SignalR.Common/Interfaces/IMultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointMessageWriter.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionContainerFactory.cs
Clean up unnecessary interface
=> We don't need an interface for multi-endpoint

src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointMessageWriter.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs
Normalize the TargetEndpoints in ctor
=> Simplify the message writer

.github/workflows/osx.yml, src/Microsoft.Azure.SignalR.Common/Interfaces/IMultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointMessageWriter.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionContainerFactory.cs, version.props
[fixing timeouts for ackable messages](https://github.com/Azure/azure-signalr/commit/a452bd19a21961616acc0481adbdb76b5537245b)
=> Release 1.16.1

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Utilities/IsExternalInit.cs
[Fix the "serverEndpoint","clientEndpoint" of ServiceEndpoint ctor](https://github.com/Azure/azure-signalr/commit/309adfdfeb3fd68436c9305980788c6f17a89a99)
=> Release 1.16.1 - patch1

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs
=> Fix flag reset in multiple endpoints reloads

src/Microsoft.Azure.SignalR.Common/Endpoints/HubServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs
=> Thread safe on scale status.

src/Microsoft.Azure.SignalR.Common/Endpoints/HubServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs
=> Release1.17 - minor fix

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs
fix issue #1603
- Detail 1
- Detail 2
=> [Hotfix] Revert change on ServiceEndpoint.Name

src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/ConnectionStringParserTests.cs
=> code cleanup before refactor parser

src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceEndpoint.cs, test/Microsoft.Azure.SignalR.Tests/ServiceMessageTests.cs
=> Hide 401 exceptions when the old key is still available

src/Microsoft.Azure.SignalR.Common/ServiceMessages/RuntimeServicePingMessages.cs, src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/MulticastDataMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocolConstants.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
[Service Protocols](https://msazure.visualstudio.com/One/_wiki/wikis/Azure%20SignalR%20Service/348056/client-invocation?anchor=service-procotols)
=> Add ClientInvocation protocol

build/dependencies.props, run.ps1, run.sh, src/Microsoft.Azure.SignalR.Common/Microsoft.Azure.SignalR.Common.csproj, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, src/Microsoft.Azure.SignalR.Serverless.Protocols/Microsoft.Azure.SignalR.Serverless.Protocols.csproj, src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj, test/Microsoft.Azure.SignalR.Serverless.Protocols.Tests/Microsoft.Azure.SignalR.Serverless.Protocols.Tests.csproj
This reverts commit a932b4752852c6da4582dc5b4cc4f00ac40d6579.
- Revert "Upgrade to .NET 7 (#1658)"
=> Revert "Upgrade to .NET 7 (#1658)"

src/Microsoft.Azure.SignalR.Common/ServiceConnections/AckStatus.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs
To fix https://github.com/Azure/azure-signalr/issues/1660 from SDK side
=> Add InternalServerError to retryable error

build/dependencies.props, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ClaimsUtility.cs, src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs, src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs
=> Implement close on client authentication expiration

src/Microsoft.Azure.SignalR.Common/ClientInvocation/DummyClientInvocationManager.cs, src/Microsoft.Azure.SignalR.Common/ClientInvocation/IClientInvocationManager.cs, src/Microsoft.Azure.SignalR.Common/ClientInvocation/IClientResultsManager.cs, src/Microsoft.Azure.SignalR.Common/ClientInvocation/IRoutedClientResultsManager.cs, src/Microsoft.Azure.SignalR/ClientInvocation/CallerClientResultsManager.cs, src/Microsoft.Azure.SignalR/ClientInvocation/ClientInvocationManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/DefaultClientInvocationManager.cs
=> [ClientInvocation] Fix cleanup in caller case.

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, test/Microsoft.Azure.SignalR.Management.Tests/DependencyInjectionExtensionFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/Microsoft.Azure.SignalR.Management.Tests.csproj, test/Microsoft.Azure.SignalR.Management.Tests/RestHealthCheckServiceFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/Serialization/SerailizerFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/StronglyTypedServiceHubContextFacts.cs
=> Fix proxy not applied to serverless transient mode

version.props
=> Update dev to 1.19.1

test/Microsoft.Azure.SignalR.Common.Tests/BackOffPolicyFacts.cs, test/Microsoft.Azure.SignalR.Common.Tests/CustomizedTimerTests.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs, test/Microsoft.Azure.SignalR.E2ETests/SignalR/TestStartup.cs, test/Microsoft.Azure.SignalR.Tests.Common/VerifiableLoggedTest.cs
Add a `RetryWhenExceptionThrows` method for some fail-prone cases.
=> Fix test cases

src/Microsoft.Azure.SignalR.Common/RestClients/SignalRServiceRestClient.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/Internal/WebSocketsTransport.cs, src/Microsoft.Azure.SignalR.Common/Utilities/RestApiEndpoint.cs, src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, test/Microsoft.Azure.SignalR.Common.Tests/RestClients/RestClientFacts.cs
=> some code cleanup for rest api

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, test/Microsoft.Azure.SignalR.Tests/ServiceMessageTests.cs
Fix https://github.com/Azure/azure-signalr/issues/1707
=> Change connection drop related log to info since the impact is little

docs/management-sdk-guide.md, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, src/Microsoft.Azure.SignalR.Management/Serialization/JsonObjectSerializerHubProtocol.cs, src/Microsoft.Azure.SignalR.Management/Serialization/SerializationDependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerBuilder.cs, test/Microsoft.Azure.SignalR.Management.Tests/Microsoft.Azure.SignalR.Management.Tests.csproj, test/Microsoft.Azure.SignalR.Management.Tests/Serialization/SerailizerFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/Serialization/WithHubProtocolFacts.cs, version.props
Add method `ServiceManagerBuilder.WithHubProtocols`, `ServiceManagerBuilder.AddHubProtocol`
=> Support MessagePack for persistent mode

src/Microsoft.Azure.SignalR/Internals/DefaultHubMessageSerializer.cs, test/Microsoft.Azure.SignalR.Tests/HubMessageSerializerTests.cs
- find hub protocol, ignore case
=> fix hub protocol bug

src/Microsoft.Azure.SignalR.Protocols/ArrayDictionary.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs
Minor fixes to ArrayDictionary 
Getting rid of extra memory allocations
=> Fixes for ArrayDictionary and extra memory allocations

docs/management-sdk-guide.md
=> Fix typo in management-sdk-guide.md

src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/UriExtensions.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AadAccessKeyTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/ConnectionStringParserTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceEndpointFacts.cs
- Add ServerEndpoint support for Azure AD scenario 
Fix #1802
=> Add ServerEndpoint support for Azure AD scenario

src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/UriExtensions.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, src/Microsoft.Azure.SignalR.Common/Utilities/RestClient.cs, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AadAccessKeyTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/ConnectionStringParserTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceEndpointFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/DependencyInjectionExtensionFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerOptionsFacts.cs, version.props
=> Release 1.21.5

specs/ClientInvocation.md
=> update doc about client invocation limits.

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/RuntimeServicePingMessages.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
- Add connection id in handshake response.
- Add echo in ping message.
=> add connection id in handshake response and add echo in ping.

specs/ServiceProtocol.md
=> Add echo in ServiceProtocol.

version.props
=> Update dev to 1.21.7

src/Microsoft.Azure.SignalR.Common/Endpoints/AccessKeySynchronizer.cs
=> update key synchronizer log

src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs
=> reformat ClientContext.cs and ServiceConnection.cs

src/Microsoft.Azure.SignalR/ClientInvocation/CallerClientResultsManager.cs
Update exception type for client invocation
=> Update exception type for client invocation

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/Utilities/AckHandler.cs, test/Microsoft.Azure.SignalR.Tests/AckHandlerTest.cs
1. Add multiple ack for `AckHandler`.
2. Refactor it
=> Add mutli ack to AckHandler
