samples/ChatSample/ChatSample.csproj, samples/ChatSample/Hub/NotificationHub.cs, samples/ChatSample/Startup.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/HubHost/IServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs
Fixes https://github.com/Azure/azure-signalr/issues/97
We were starting multiple instances of the same ServiceConnection per hub since IServiceConnectionManager was a singleton. The fix is to make the `IServiceConnectionManager` specific to a hub so that the ServiceHubDispatcher gets a different instance per hub.
I couldn't think of a good way to test this but the sample has 2 hubs now 😄
=> Support multiple hubs

korebuild-lock.txt, test/Microsoft.Azure.SignalR.Protocols.Tests/Microsoft.Azure.SignalR.Protocols.Tests.csproj, test/Microsoft.Azure.SignalR.Tests/Microsoft.Azure.SignalR.Tests.csproj
Korebuild's config for dotnet SDK needs to be updated. Otherwise, it reports exception:
"Could not load file or assembly 'System.Memory, Version=4.1.0.0, Culture=neutral,
PublicKeyToken=cc7b13ffcd2ddd51'"
dotnet 2.1.300-rc1-008673 works fine. But lower version has this issue.
=> fix issue #99

src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs, src/Microsoft.Azure.SignalR/HubHost/TimerAwaitable.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceContextFacts.cs
Send `PingMessage` from server to service every 5 seconds, so that service can quickly detect an unresponsive service connection.
=> send PingMessage to service to keep alive

src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/HubHost/ClientConnectionFactory.cs, src/Microsoft.Azure.SignalR/HubHost/IClientConnectionFactory.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceConnectionContext.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs
- Manually write the message pack header and ReadOnlySequence to the Stream directly.
Fixes #124 
PS: I need to write tests. We also need to update the logic in the service that writes to the transport.
=> Write the ReadOnlySequence as a single ConnectionDataMessage

src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs
For ServiceConnection Handshake, for better debugging experience
=> Avoid connection timeout when debugger is attached

src/Microsoft.Azure.SignalR/HubHost/ServiceConnection.cs
> Performance tip: It's more efficient to loop over the ConcurrentDictionary itself rather than keys or values. Each of those collections takes a lock on all of the buckets.
=> Loop over the dictionary itself rather than keys

src/Microsoft.Azure.SignalR.AspNet/Microsoft.Azure.SignalR.AspNet.csproj
Although `PrivateAssets` and set workarounds as https://github.com/nuget/home/issues/3891#issuecomment-397481361 shows, it is unable to detect what Common project references and build process is unable to add it to the references of current project automatically.
So for now, we still need to make sure the references of Common project is added to this project's references, until https://github.com/nuget/home/issues/3891 is resolved.
=> Add dependencies from Common project to here

src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs
fix issue [#198](https://github.com/Azure/azure-signalr/issues/198)
=> rename custom header name to avoid header restriction in asp.net framework

src/Microsoft.Azure.SignalR/NegotiateHandler.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs
Bug: add our custom user id in the claim when the user id is null, this will prevent using the standard name identify.
=> fix claim in negotiate handler.

src/Microsoft.Azure.SignalR.Common/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocolConstants.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs
* As customer can't get any error messages when service terminate the server connections now, it will be very confusing when service reach message limit. Under that circumstance, server will keep reconnecting without any useful reasons.
* ServerCloseMessage is used to send back error messages from service before service abort the connection. There are some changes in service to enable the workflow and in SDK, we just log these error messages.
* This is not a breaking change, old sdk can work with new service and vice versa.
=> Add ServerCloseMessage to protocol

src/Microsoft.Azure.SignalR.Common/ServiceConnectionBase.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceConnectionBaseTests.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestConnectionFactory.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs
When app server failed to handshake with service, it will stop connect.
But the app server will running to a strange state:
1. app server is alive
2. app server never connect to service, even issues in service are gone.
3. customer must restart the app server to reconnect with service, and in most case customer have to restart it manually.
Solutions:
1. [ ] stop app server when all server connections are broken.
Big impact when service has some temporary issue.
2. [x] retry to connect service for ever.
=> reconnect when handshake failed.

src/Microsoft.Azure.SignalR.Common/ServiceConnectionBase.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs
Change ping trigger way by any incoming requests and send ping if it's longer than 5 seconds since last.
Service ping interval is updating to 5 seconds already.
=> Improve keep alive ping reliability

test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs
Add 1 second waiting after receive ping because send ping is a separate task which might have some delay to update the _lastSendTimestamp and leads to test case failure.
=> Fix UT random failure

src/Microsoft.Azure.SignalR.AspNet/Infrastructure/ServiceConnection.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/Infrastructure/TestTransport.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceConnectionTests.cs
In normal case, close connection message is the last message in channel to process and no need to wait application task anymore.
In abnormal case, loop break for channel exception/cleanup connections, no need to wait for application task as well.
=> Simplify channel logic and fix bug

src/Microsoft.Azure.SignalR.AspNet/HubHost/NegotiateHandler.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/DefaultRouter.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs, src/Microsoft.Azure.SignalR.Common/Exceptions/ServiceConnectionNotActiveException.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IEndpointRouter.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceEndpointManager.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/StrongServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/WeakServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceMessageBusTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceConnectionContainerFacts.cs, test/Microsoft.Azure.SignalR.Common.Tests/TestServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests/AddAzureSignalRFacts.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs
When `connection` is null, consider it as `online` to be compatible with current behavior. 
TODO:
=> Add fallback to GetPrimaryEndpoints when all primary endpoints are offline

build/dependencies.props
HttpConnections.Client 1.1.0 solves the `stack empty` exception when disposing the connection
=> Upgrade from 1.0.0 to 1.1.0

build/dependencies.props, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceConnectionTests.cs
This reverts commit 9fe2a1dde3b7ec3324b6c30cc8cd0686544702b0.
1.1.0 HttpConnections.Client requires .Net Core 2.2, which is a breaking change for users of .Net Core 2.1. Versions should be taken care carefully in our SDK. We should not upgrade version until we settle down a way to handle multiple versions.
=> Revert "Upgrade from 1.0.0 to 1.1.0 (#403)"

docs/rest-api.md
* Port 5002 was removed.
* `v1-preview` will be deprecated.
* `v1` is available.
=> Update document for REST API

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs, test/Microsoft.Azure.SignalR.Tests/AddAzureSignalRFacts.cs, test/Microsoft.Azure.SignalR.Tests/Microsoft.Azure.SignalR.Tests.csproj
Fix #439 
Fix false warning message
`2 endpoints to https://northstardevsignalr.service.signalr.net found, use the one https://northstardevsignalr.service.signalr.net`
This is caused when connection string is configured in Configuration, it is counted twice, both into `ConnectionString` and `Endpoints`
=> Fix the false warning for connectionstring

src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, test/Microsoft.Azure.SignalR.Management.Tests/UnitTests/ServiceManagerFacts.cs
=> Fix bug: If input null for loggerFactory, use default one in AddLogging()

samples/AspNet.ChatSample/AspNet.ChatSample.SelfHostServer/Startup.cs, samples/AspNet.ChatSample/AspNet.ChatSample.SelfHostServer/app.config, src/Microsoft.Azure.SignalR.AspNet/TraceManagerLoggerProvider.cs
to one single source `Microsoft.Azure.SignalR` so that it is easier to enable the trace. Also add a sample config in the sample project.
The Trace system in ASP.NET requires one to know the full name of the TraceSource to configure the trace settings. In our current design, the name of the TraceSource is the full name of the classes logging the trace. We also have logs from the underlying `HttpConnection`. As a result, users need a long list of TraceSource names to collect all the logs from our SDK.
This PR is to change the TraceSource name to `Microsoft.Azure.SignalR` and move the class name to the trace message so that it is easier to config.
=> Consolidate the trace source for ASP.NET SignalR

test/Microsoft.Azure.SignalR.Management.Tests/E2ETest/ServiceHubContextE2EFacts.cs
some users may set the service mode to default mode, which will result in dropping client connections when the 1st message (including ping messages) reaches the service.
handle the hub connection closed event will indicate that the error probably caused by external env, e.g. the service is unavailable/ service mode is incorrect
=> handle hub connection closed event

Directory.Build.props, build/package-test.3.proj, build/package-test.proj, build/repo.props, build/sign.proj, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj, test/Microsoft.Azure.SignalR.Tests/AzureSignalRMarkerServiceFact.cs, version.props
1. Add `IsTargetMultiFramework` to configure different version build/deploy.
2. Assign files to sign due to limitation in KoreBuild for multiframework.
3. Fix UT.
=> Separate build for different framework versions

samples/AspNet.ChatSample/AspNet.ChatSample.SelfHostServer/Program.cs, src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs
as for AspNet it requires Azure SignalR Service runtime side support to make it work
=> Add back the option to disable application prefix for aspnet 

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs
Service side is ready for this prefix change
=> Enable application name as prefix for ASP.NET SignalR

src/Microsoft.Azure.SignalR.Common/Endpoints/HubServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/WeakServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/ServicePingMessageExtension.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/ServiceStatusPingMessage.cs, test/Microsoft.Azure.SignalR.Common.Tests/WeakServiceConnectionContainerTests.cs
The service returns `active` ping message when there is any client connected to it, and returns `inactive` ping message when there is no client connected to it. 
For weak connections, there is no need to send server->client messages to a `inactive` service.
From SDK side, we check service status every 10 seconds, whenever we get an `active` ping message, we consider the service as `active`. When we get at least 5 continuous `inactive` ping messages in at least 10 minutes, we consider the service as `inactive`.
Due to the delay of the `active`/`inactive` status, we only enable this for weak connections.
=> Add service active check to weak connections

AzureSignalR.sln, test/Microsoft.Azure.SignalR.E2ETests/Microsoft.Azure.SignalR.E2ETests.csproj
Put all e2e tests into this project later.
Avoid breakding change conflict in `Azure SignalR SDK Signing` pipeline for HttpClientConnection which is referenced by both SignalR client and Azure SignalR SDK.
E2E test will not run in  `Azure SignalR SDK Signing` pipeline, only in nightly build.
=> add a e2e test project

docs/use-signalr-service.md, src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, test/Microsoft.Azure.SignalR.Tests/AddAzureSignalRFacts.cs
This reverts commit e240ca8116ca67c84417d9175e3e0649746e6654.
Rebalance server connection is not yet supporting sending messages from server to client. So we still need more initial server connections for now.
=> Revert commit e240ca8 for "Use 2 as the default connection count"

test/Microsoft.Azure.SignalR.Tests/Microsoft.Azure.SignalR.Tests.csproj, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs
From AspNetCore 3.0 preview7, there's a break change in HubConnectionContext which will break cross reference for a NETCOREAPP 3.0 reference NETStandard2.0 SDK case. 
This part of test is already covered under NETCOREAPP 3.0 reference NETCOREAPP 3.0 SDK. So skip this part of UT when target 2.0 only.
=> Fix UT under cross reference scenario for preview7

src/Microsoft.Azure.SignalR.AspNet/ClientConnections/ClientConnectionManager.cs, src/Microsoft.Azure.SignalR.AspNet/ClientConnections/IClientConnectionManager.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.AspNet/Transports/AzureTransport.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ClientConnectionManagerTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceMessageBusTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/SignalRMessageParserTest.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/SignalRMessageUtility.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestClientConnectionManager.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestServiceConnectionHandler.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/EndlessConnectHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/EndlessInvokeHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/ErrorConnectHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/ErrorDisconnectHub.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestHubs/ErrorHub.cs, test/Microsoft.Azure.SignalR.Tests.Common/VerifyNoErrorsScope.cs
1. Case 1: , when OnConnected throws, the exception is swallowed, and Disconnected will never trigger
2. Case 2: when client connection closed, the client manager never cleans the disconnected connection
=> Fix aspnet application exception cases

src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs
For #473 
With this change, QueryString and Headers can be fetched from `Hub.Context.Request`. User is still getting `null` from `Hub.Context.GetHttpContext()` though.
=> Preserve user query string for aspnet

build/dependencies.props, src/Microsoft.Azure.SignalR.AspNet/Microsoft.Azure.SignalR.AspNet.csproj, src/Microsoft.Azure.SignalR.Common/Microsoft.Azure.SignalR.Common.csproj, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestConnectionFactory.cs
For AspNet SDK, we've had several customers reporting writing messages slow/hung.
It happens that we are using a quite old version of System.IO.Pipeline and there have been quite a few fixes happened to System.IO.Pipeline related to `WriteAsync`: https://github.com/dotnet/corefx/commit/00c43bd29cd408db3b6b4a8255f32a8f420024ca#diff-9a0b343d0ae95ef90f79dcc5a297c613
Upgrade to the latest version and explicitly use the latest pipeline in SDK projects.
=> Upgrade pipeline version and channel version

.gitignore, src/Microsoft.Azure.SignalR.AspNet/ClientConnections/ClientConnectionManager.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IClientConnectionLifetimeManager.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR/ClientConnections/ClientConnectionManager.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnectionContext.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ClientConnectionManagerTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestClientConnectionManager.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests/ClientConnectionManagerTests.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionContainerBaseTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.Tests/TestSimpleServiceConnection.cs
Related to #689 
1. Add `ConnectionOfflineTask` for `IServiceConnection`
- Use for waiting for a server connection to be offlined.
2. Add `AllConnectionsCompleted` for `IClientConnectionLifetimeManager`
- Use for waiting for existing client connections to be stopped.
=> Add Interfaces for `Graceful shutdown`

.gitignore, src/Microsoft.Azure.SignalR.AspNet/DispatcherHelper.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/StrongServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/WeakServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR/ServerConnections/IServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR/ServiceOptionsSetup.cs, src/Microsoft.Azure.SignalR/ServiceRouteBuilder.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/TestClasses/TestClientConnectionManager.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestBaseServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestServiceConnectionManager.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionContainerBaseTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceHubDispatcherTests.cs, test/Microsoft.Azure.SignalR.Tests/TestServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests/TestServiceConnectionForCloseAsync.cs
The target of this PR is to ensure all incoming and outgoing packages will be processed before a scheduled shutdown. 
**UPDATE 11/13**
> 1. Add test cases for `HubDispatcher` and `MultiEndpointContainer`.
**UPDATE 11/12**
> 1. Lift the `ShutdownAsync` method up to the `HubDispatcher` level.
**UPDATE 11/06**
> 1. Lift the `ShutdownAsync` method up to the `MultiEndpointServiceConnectionContainer` level.
> 2. Add `OfflineAsync` method to `IServiceConnectionContainer`.
**UPDATE 11/05**
> 1. Move `CloseAsync` method to `ServiceConnectionContainer` level.
**UPDATE 11/01**
> 1. Replace **CloseConnectionMessage** with **PingMessage**.
> 2. Wait on TCS instead of connection **outgoing tasks**.
> 3. Prevent rebalanced (ondemand) connection from starting in the shutdown process. 
**UPDATE 10/31**
> …
=> Graceful shutdown support

samples/ChatSample/ChatSample/Startup.cs, src/Microsoft.Azure.SignalR.AspNet/ClientConnections/ClientConnectionManager.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/StrongServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/ServiceLifetimeManagerFacts.cs
We almost have all kinds of messages sending to our `ServiceConnection` directly in the existing codes.
Only `sendToConnection` will be sent to `HubContext` and I redirected it to `ServiceConnection` in this PR to fit the rules we are following now.
- And also add an `EchoHub` for our `ChatSample`, which will let our customers doing their perf test easier.
=> Redirect send2conn from sending to Hub to SvcConn

.gitignore, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/StrongServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestClientConnectionFactory.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestConnectionFactory.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceContextFacts.cs
Related to #689 
The migration will start on the `Runtime` side after the graceful shutdown process begins.
And there is nothing to do with **the old server**. 
> we simply close each connection after receiving `CloseConnectionMessage`.
But we have to prevent `HandshakeResponse` from reaching our `Runtime` after the client connection has been migrated to **the new server** since the client connection has not been really dropped by our `Runtime`. It would be weird if we sent `HandshakeReponse` to our client again.
=> Server connection migration implementation

src/Microsoft.Azure.SignalR.Common/Utilities/CancellationTokenExtensions.cs, src/Microsoft.Azure.SignalR.Common/Utilities/TaskExtensions.cs, src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs
Add an AbortConnection token to aspnetcore ServiceConnection so that the ClientConnection process loop can be aborted, also some minor format changes
=> Add an AbortConnection token to aspnetcore ServiceConnection

src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs
The idea of this PR is the same as the already Merged PR #534 
This issue has been created to address `ServiceManager` connectivity throught a proxy,
i tried to provide a PR #727 
The `ServiceManager` rely on the `ServiceEndpointProvider` for connectivity
the `ServiceEndpointProvider` already `ServiceOptions` which already has Proxy support (see #534 / #535)
The idea is just to add an `IWebProxy` property to the `ServiceManagerOptions` so that is can be forwarded to the `ServiceEndpointProvider` through the `ServiceOptions` :
```
_endpointProvider = new ServiceEndpointProvider(_endpoint, Options.Create(new ServiceOptions
{
// ....
Proxy = serviceManagerOptions.Proxy
}));
```
=> Add proxy support for the ServiceManager from ServiceManagerOptions

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs
Fixing #675 by keeping the connection Status property in sync with the state of the service connection.
When a service sends ServiceErrorMessage to the App Server it won't be able to accept new messages. App Server should mark this connection as disconnected immediately to prevent sending new messages to it.
=> fixing #675 by keeping the Status property in sync with the state of the service connection

src/Microsoft.Azure.SignalR/Startup/NegotiateMatcherPolicy.cs
Controller is also an Endpoint which should not be converted to negotiate endpoint. Add check for RouteEndpoint only before converting specifically.
Fix #777.
=> Fix apply negotiate endpoint in .NET Core 3.0

src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs
There can be a race, when `ServiceConnection` tries to `CleanupClientConnections` and completes the client's `Application.Output` while client connection is writing messages to it.
=> Move complete application.output into the client connection

src/Microsoft.Azure.SignalR/Startup/NegotiateMatcherPolicy.cs, version.props
RouteEndpoint may not apply hub and could be null before get HubType. Skip this kind of endpoint when redirect service.
=> Fix blazor bug

src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/HubHost/ServerLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnectionFactory.cs, src/Microsoft.Azure.SignalR/ServiceRouteBuilder.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceHubDispatcherTests.cs
According to our latest change for the `.NetCore 3.0`, which is using reflection to get `HubDispathcer` and starting it.
We introduced a singleton instance `ServerLifetimeManager` to register shutdown hooks and account for the **graceful shutdown**.
And also,
1. Some default value changes. (timeout, migration level)
2. Add required properties. (migration level)
=> Refactor about HubDispatcher

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AccessKey.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Utilities/AuthUtility.cs, src/Microsoft.Azure.SignalR.Management/RestApiAccessTokenGenerator.cs, src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, test/Microsoft.Azure.SignalR.Common.Tests/AuthenticationHelperTest.cs, test/Microsoft.Azure.SignalR.Tests/JwtTokenHelper.cs, test/Microsoft.Azure.SignalR.Tests/ServiceEndpointProviderFacts.cs
Introduce a new object type `AccessKey` to storage the relationship between `AccessKey` and its `KeyId`, even expiration time in the future.
=> [AAD] AccessKey object

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AccessKey.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ConnectionFactory.cs, src/Microsoft.Azure.SignalR.Management/IServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs, src/Microsoft.Azure.SignalR/Utilities/ServiceRouteHelper.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs, test/Microsoft.Azure.SignalR.Tests/ServiceEndpointProviderFacts.cs
Since a server-generated `AccessKey` may need to be authorized in the future. Change the `GetAccessToken` methods to **async** (for both server and client connections)
=> [AAD] make GetAccessToken async

.gitmodules, 3rdPartyNotices.txt, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
In old version 2.0 of `MessagePack`, when message length > 64K, the length is treated as `Int64` for `ReadOnlySequence`, however, according to the spec of `MessagePack`, it should be at most treated as `Int32`. The latest version 2.1.115 fixed the issue.
This issue is causing: message length > 64K is not able to get delivered to service.
=> Update messagepack version

test/Microsoft.Azure.SignalR.Management.Tests/RestApiProviderFacts.cs
IDE will cache string before real test, test will be run in a new process, result in value of GetHashCode() generate in real test (in a new process) is different to the one in the cache. 
To prevent the cache, pass the data as a reference type.
=> Fix unit test

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/WeakServiceConnectionContainer.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionFactory.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs
Move active to ServiceEndpoint so that user can decide whether to send messages or not instead of making it a default behavior of weak connections
=> Move active to ServiceEndpoint so that user can decide whether send or not

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/WeakServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Management/IServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/RestApiProviderFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionFactory.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs, version.props
1. Revert the interface breaking change in Management SDK (#876)
2. Add a `IsActive` property to `ServiceEndpoint` so that user can decide if sending message to an endpoint having no client connections. (#879)
=> Release V1.4.3

src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, src/Microsoft.Azure.SignalR.Management/RestClient.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs, test/Microsoft.Azure.SignalR.Management.Tests/RestApiProviderFacts.cs
Plan to add more REST APIs in Management SDK.
Plan to add check-service-health API to IServiceManager, so:
1. extract the `RestClient` from `RestHubLifetimeManager` for better reuse.
2. refactor `RestApiProvider` make it support APIs without hub name.
=> Extract rest client

src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/GroupMessage.cs, src/Microsoft.Azure.SignalR.Protocols/IMessageWithTracingId.cs, src/Microsoft.Azure.SignalR.Protocols/MulticastDataMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
Allow adding more optional members in future.
Serialize and deserialize optional members.
We will have more optional members in near future.
* Tracing Id -  for diagnosis
* Sequence Id - for ordering in some special time (client connection switch to another server connection in the same server).
We cannot use current length based deserializing to detect which field occurred.
Add a map field represent all optional fields in the binary.
* All of optional fields should write in this field.
* Non-optional fields are not recommended in this field.
* Key is field hint for identifying the optional field (e.g.: tracing id is 1).
* Value is the real value for the optional field.
The original format for `ConnectionDataMessage` is:
```
[(type)6, (ConnectionId) "abc", (payload) binary]
```
Updated …
=> add extensible members in protocol.

src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR.Protocols/GroupMessage.cs, src/Microsoft.Azure.SignalR.Protocols/MulticastDataMessage.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceMessageEqualityComparer.cs, test/Microsoft.Azure.SignalR.Protocols.Tests/ServiceProtocolFacts.cs
Tracing id is only used for message that contains customer's data, includes group action messages, connection data message and multicast messages, and _excludes_ ping/handshake/ack message.
=> Update service protocal for message's tracing id

docs/use-signalr-service.md, src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointManager.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, test/Microsoft.Azure.SignalR.Tests.Common/TestClasses/TestServiceConnectionContainer.cs
Turn on the switch to enable dynamic scale `ServiceEndpoint`.
=> Enable dynamic scale service endpoints.

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ClientConnectionScope.cs
...before storing it in async local to prevent memory leaks.
Execution contexts may keep ServiceConnection alive for much longer than the actual service connection lifetime. So we wrap it in a weak reference before storing in async local.
=> Wrapping IServiceConnection in WeakReference 

src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, src/Microsoft.Azure.SignalR.AspNet/ServiceOptions.cs, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ClaimsUtility.cs, src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.Tests/AddAzureSignalRFacts.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs
There is a scenario for [_message log feature_](https://microsoft.sharepoint.com/teams/IoTToolingTeam/_layouts/OneNote.aspx?id=%2Fteams%2FIoTToolingTeam%2FSiteAssets%2FAzure%20SignalR%20Service%20Notebook&wd=target%28SignalR%20Service%20-%20SignalR%20Service%20-Engineering%20Doc.one%7CCE337738-D146-4D4C-B03E-9FFF6F433FCD%2F-%20%5BWIP%5D%20Improve%20Customers%27%20Experience%3A%20Message%20Log%7C38C10298-91B4-4D6C-9B34-93B4B29C8E4C%2F%29) that customers only want to add message logs for some specific clients. i.e. _tracking clients_. To support this, app server sould need to support filter client connections to tell which clients are _tracking clients_.
This PR add a new option in `ServiceOption` to let customers determine which are _tracking client_ based on `HttpContext`. Server SDK add …
=> Add TrackingClientFilter in ServiceOption

src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs
When the connected client exits, app server always reports error like below:
```
fail: Microsoft.Azure.SignalR.ServiceConnection[8]
Application task failed.
Microsoft.Azure.SignalR.Common.AzureSignalRException: Cancelled running application task, probably caused by time out.
at Microsoft.Azure.SignalR.ServiceConnection.ProcessIncomingMessageAsync(ClientConnectionContext connection) in C:\repos\signalr-sdk\src\Microsoft.Azure.SignalR\ServerConnections\ServiceConnection.cs:line 391
at Microsoft.Azure.SignalR.ServiceConnection.ProcessClientConnectionAsync(ClientConnectionContext connection) in C:\repos\signalr-sdk\src\Microsoft.Azure.SignalR\ServerConnections\ServiceConnection.cs:line 227
```
This is because when `OnClientDisconnectedAsync` it always cancel input read first. It does not …
=> fix the issue that when client exit app server reports tedious error

emulator/Microsoft.Azure.SignalR.Emulator/AppBuilderExtensions.cs, emulator/Microsoft.Azure.SignalR.Emulator/Common/SignalRServiceWebApiDefinition.cs, emulator/Microsoft.Azure.SignalR.Emulator/Microsoft.Azure.SignalR.Emulator.csproj, emulator/Microsoft.Azure.SignalR.Emulator/Startup.cs, emulator/Microsoft.Azure.SignalR.Emulator/appsettings.json
*Changes*
1. Make internal Controller class work
2. Print out the connection string when the emulator starts
3. Add Auth to Controller
4. No need to have accessKey configurable
Current console when emulator runs:
=> [emulator] Minor tweaks to make emulator work

src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs
- remove condition for warning log, since other warning log about message is always logged
- move condition out of logging functions
- use tracing id as condition for logging. It's enough, and more accurate, since diagnostic client always generate tracing id for wanted log (filter out ping messages, control messages, etc), and tracing is always available for service message to be sent to service when "collect all" or the source is diagnostic client
=> improve message logs

src/Microsoft.Azure.SignalR.Common/Endpoints/EndpointMetrics.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/EndpointStat.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/RuntimeServicePingMessages.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs, test/Microsoft.Azure.SignalR.Tests/TestServiceConnectionContainer.cs
Store global client connection count in ServiceEndpoint to enable server side do customized routing in sharding.
=> Store global client connection from ping.

src/Microsoft.Azure.SignalR.AspNet/EndpointRouters/DefaultEndpointRouter.cs
This PR fixes a typo that was found in `DefaultEndpointRouter.cs `
=> fix typo availbaleEndpoints => availableEndpoints

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpointManagerBase.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointManager.cs, test/Microsoft.Azure.SignalR.Tests/AddAzureSignalRFacts.cs, test/Microsoft.Azure.SignalR.Tests/testappsettings.json
- Use `GetEndpoints` when reload to apply all available settings.
Fixes #1048
=> Fix reload endpoints

docs/howto-tsg.md
The original Url does not appear to work. It was returning 404 for the free tier Azure SignalR instances and 403 for standard tier ones. 
I believe I found the one that works, the updated url returns 200 for all of the SignalR instances that I was able to test, and during an Azure SignalR restart it would switch to 502s.
Changed the health check url in the documentation.
=> Updated the healthcheck url.

src/Microsoft.Azure.SignalR.AspNet/OwinExtensions.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs
For `ASP.NET MVC`, users can call hub methods using `GlobalHost.ConnectionManager.GetHubContext<Hub>()` in it's Controller with `AspNetSynchronizationContext`. Adding `ConfigureAwait(false)` to prevent message send from relying on this context.
=> Add ConfigureAwait false

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, src/Microsoft.Azure.SignalR/EndpointProvider/DefaultServiceEndpointGenerator.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, test/Microsoft.Azure.SignalR.Common.Tests/ConnectionStringParserFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs
User can add `ClientEndpoint={url}` in connectionstring to customize the target endpoint for client to redirect to.
=> Add ClientEndpoint support to ConnectionString to customize client negotiate target

src/Microsoft.Azure.SignalR.Management/ServiceManagerOptions.cs
- change `ServiceEndpoint` in `ServiceManagerOptions` accesibility to internal as AAD service endpoint will be configured as connection string . It will be deleted later.
=> mark ServiceEndpoint in ServiceManagerOptions as internal 

docs/use-signalr-service.md
Renamed `option` variable to `options` in the following code sample:
services.AddSignalR()
.AddAzureSignalR(options =>
{
options.ConnectionCount = 10;
options.AccessTokenLifetime = TimeSpan.FromDays(1);
options.ClaimsProvider = context => context.User.Claims;
option.GracefulShutdown.Mode = GracefulShutdownMode.WaitForClientsClose;
option.GracefulShutdown.Timeout = TimeSpan.FromSeconds(10);
});
=> Fixed options variable name in one of code samples

samples/ChatSample/ChatSample/Startup.cs, samples/ChatSample/ChatSample/wwwroot/index.html, src/Microsoft.Azure.SignalR.AspNet/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR/GracefulShutdownOptions.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceHubDispatcher.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnectionManager.cs, test/Microsoft.Azure.SignalR.IntegrationTests/Infrastructure/MockServiceHubDispatcher.cs, test/Microsoft.Azure.SignalR.Tests/ServiceHubDispatcherTests.cs, test/Microsoft.Azure.SignalR.Tests/TestHubContext.cs
Add a new step for **graceful shutdown** feature.
Now the graceful shutdown works in the following order.
1. Set the server offline from ASRS.
2. **(New) Trigger OnShutdown hooks.**
3. Wait until all client connections have finished, depends on the mode (Wait/Migrate) you choose.
4. Stop server connections.
As well as fixed a bug that will cause `OperationCancelledException` when the given endpoint is not accessible.
=> Add hooks for Graceful shutdown

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointManager.cs, src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.AspNet/Middleware/NegotiateMiddleware.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs, src/Microsoft.Azure.SignalR.Common/Exceptions/AzureSignalRAccessTokenNotAuthorizedException.cs, src/Microsoft.Azure.SignalR/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR/Utilities/ServiceRouteHelper.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs
1. Throw `AzureSignalRAccessKeyNotAuthorizedException` while the given Accesskey doesn't have permission to generate `AccessToken` for clients.
2. Add exception handler for both `ASP.NET Core SignalR` and `ASP.NET SignalR`.
=> Throw exc while key doesn't have read accesskey permit.

src/Microsoft.Azure.SignalR.Management/Configuration/ContextOptions.cs
- internalize`ProductInfo` and `ServiceTransportType` in `ContextOptions`
=> Not allow user to configure some properties in ServiceContext

src/Microsoft.Azure.SignalR.Management/IServiceContext.cs
Because function extension will use `IServiceContext` as a constructor parameter in a `public` class
=> make IServiceContext public for function extension

src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs
The actual impl of `IServiceProvider` can not be converted to `ServiceProvider`.
=> fix fail to dispose service provider inside ServiceHubContext

src/Microsoft.Azure.SignalR.Emulator/Controllers/SignalRServiceEmulatorWebApi.cs
`Microsoft.Azure.SignalR.Emulator.Controllers.SendAsync` will error if `object[] arguments` is null.  `arguments` is not required on the `SignalRMessage` class and therefore could very well be null.
=> fixed null reference error when arguments is not supplied/null

src/Microsoft.Azure.SignalR.Common/Utilities/RestClient.cs, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs
The REST client currently uses the default serialization settings, but it would be very helpful to change the settings (e.g. to enable camel case for property serialization).
=> Extended service manager options to configure JSON serialization

src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs
- Add services from `ServiceManager` to the `ServiceHubContext` created from `ServiceHubContext.WithEndpoints()` , rather than `AddSignalR().Services`, so that we can specify `IHubProtocol` instead of the default protocol added by `AddSignalR()` when create `ServiceManager`.
Azure Function runtime v3 uses .Net framework version higher than Net Core 3.0, which uses System.Text.Json instead of Newtonsoft.Json as the default Json protocol of SignalR. To make our function extension compatible with Azure Function v2 and v3, function extension will use Newtonsoft.Json as the SignalR protocol.
=> Allow to choose SignalR hub protocol in management SDK

test/Microsoft.Azure.SignalR.IntegrationTests/Infrastructure/HotReloadIntegrationTestStartup.cs, test/Microsoft.Azure.SignalR.IntegrationTests/Infrastructure/IntegrationTestStartup.cs
Ignore connection strings from test environment (only use dummy ones hardcoded in the tests).
=> Ignoring connection string from environment

test/Microsoft.Azure.SignalR.Management.Tests/NegotiateProcessorFacts.cs
`NegotiateProcessor` should be work in transient mode. So remove unnecessary mock of `IEndpointRouter`.
=> Improve test to make sure negotiate processor work in transient mode.

src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs
So that the behavior with only one endpoint configured is not changed, and the code simplified.
=> Refactor ServiceManager to use one endpoint from ServiceEndpointManager

src/Microsoft.Azure.SignalR.Management/IInternalServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/NegotiateProcessorE2EFacts.cs
* `ServiceManager` uses `ServiceHubContextBuilder` to build `ServiceHubContext`.
* Move `NegotiateAsync` method from `IInternalServiceHubContext` to `ServiceHubContext` abstract class.
=> Add ServiceHubContextBuilder

src/Microsoft.Azure.SignalR.Common/Auth/AadManagedIdentityOptions.cs, src/Microsoft.Azure.SignalR.Common/Auth/ManagedIdentityType.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AccessKeyTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/ConnectionStringParserFacts.cs
- Add support for user-assigned managed identity
To choose one of the user-assigned managed identity:
```text
Endpoint={endpoint};AuthType=aad;ClientId={ClientId of user-assigned identity}
```
> There is no need to provide **TenantId** according to this [link](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication)
Doc changes are on the way : )
Fixes:
Issue #1237
=> support user-assigned managed identity

src/Microsoft.Azure.SignalR.Protocols/enums.cs
When hub servers try to send too many messages, service side will throttle the message sending, it will keep sending messages in a reasonable rate.
We add the `OverloadProtecting` event to notify app server, app server can hook it, and decrease the rate of message sending to avoid OOM in app server side.
=> add new serivce events: BufferFull

src/Microsoft.Azure.SignalR.Management/Negotiation/NegotiateProcessor.cs, src/Microsoft.Azure.SignalR.Management/Negotiation/NegotiationOptions.cs
So that when close connection from app server side, client can see the error msg.
=> Add `EnableDetailedErrors` flag to the `ServiceHubContext` negotiate options

src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs
SignalR Function extensions project doesn't use it anymore. `AddSignalRServiceManager()` sets a default product info.
`ServiceHubContextBuilder.WithCallingAssembly()` is never used
=> Remove unused code

build/dependencies.props, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, src/Microsoft.Azure.SignalR.Management/Serialization/IRestHubProtocol.cs, src/Microsoft.Azure.SignalR.Management/Serialization/JsonHubProtocolOptionsSetup.cs, src/Microsoft.Azure.SignalR.Management/Serialization/NewtonsoftHubProtocolOptionsSetup.cs, src/Microsoft.Azure.SignalR.Management/Serialization/NewtonsoftRestHubProtocol.cs, src/Microsoft.Azure.SignalR.Management/Serialization/NewtonsoftServiceHubProtocolOptions.cs, src/Microsoft.Azure.SignalR.Management/Serialization/SerializationDependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs
`_serviceProvider.GetService<IOptions<NewtonsoftServiceHubProtocolOptions>>()` is always not null, so it is wrong to use it to determine whether `ServiceHubContextBuilder.AddNewtonsoftJsonHubProtocol()` is called.
=> Add a unified way to customize JSON serialization for Newtonsoft

src/Microsoft.Azure.SignalR/ServerConnections/ClientConnectionContext.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs
To solve the issue described here https://github.com/Azure/azure-signalr/issues/1318, to be consistent with self-host SignalR, our SDK should not timeout on long-run client hub logic.
Why we have this timeout is because the client connection lifetime impacts the auto-reconnect of the server connection. When a server connection drops, it first cleans up all the existing client connections, waiting for the client connections to complete their lifetime, and then restart another server connection. If there is some malformed code inside one client hub, it can impact the whole stability of the server connection if there is no timeout.
Server connection, can be considered as the transport layer to carry traffics for some mapped client connections. Server connection drops, similar to network …
=> Server connection does not block on client connection lifetime

src/Microsoft.Azure.SignalR.Common/ServiceConnections/Internal/WebSocketsTransport.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs
The code is for intercepting `CloseMessage` to prevent the message from reaching the client before it has been logically migrated. (There is a short time period that the client connection belongs to 2 servers so we cannot simply ignore messages from the old server)
It was accidentally applied for all scenarios while doing code refactor.
#814 
And has finally been removed in the following PR to fix another issue.
#986 
Since it is a little tricky to have this logic in the server SDK, we decided to move this interceptor into our service.
So it's a work-around fix.
=> work-around fix for connection migration

src/Microsoft.Azure.SignalR.Management/ServiceManagerBuilder.cs
Prepare to merge two builder into one to reduce user migration cost.
=> Copy functions from `ServiceHubContextBuilder`  to `ServiceManagerBuilder`

build/dependencies.props, src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ConnectionService.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/HostedServiceFactory.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/MultiEndpointConnectionContainerFactory.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/RestHealthCheckService.cs, src/Microsoft.Azure.SignalR.Management/IServiceHubLifetimeManager.cs, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerImpl.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, test/Microsoft.Azure.SignalR.Management.Tests/IInternalServiceHubContextFacts.cs
Make the initialization logic unified in the `ServiceHubContextBuilder` no matter what service transport type is
=> Refactor `ServiceHubContext` initialization

Directory.Build.props, build/dependencies.props, src/Directory.Build.props, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ClaimsUtility.cs, src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, test/Microsoft.Azure.SignalR.Tests/NegotiateHandlerFacts.cs
To fixes #1325 
At first, I try to take SignalR's `HttpConnectionDispatcherOptions` option if the transport type is configured, but found that we can't get the `HttpConnectionDispatcherOptions`, so I make another options.
Usage:
```cs
.AddAzureSignalR(o =>
{
o.ConnectionString = DefaultConnectionString;
o.TransportTypeDetector = context => ...;
})
```
If user set the `TransportTypeDetector`, then a claim will be added to the access token.
CliamType: `asrs.u.htt`   Value: the int number of the `HttpTransportType` flag.
If user doesn't set the `TransportDetector`, then no related claim.
=> Allow to configure `HttpTransportType` for server SDK

src/Microsoft.Azure.SignalR/HubHost/NegotiateHandler.cs
The final usage of the `IEnumerable<Claim>` in our code is 
https://github.com/Azure/azure-signalr/blob/e8e113ff3b61603f46a5d20c965a9d56192853b2/src/Microsoft.Azure.SignalR.Common/Auth/AuthUtility.cs#L31
And `ClaimsIdentity` creates a `List<Claim>` itself and adds the claims to the list. 
https://source.dot.net/#System.Security.Claims/System/Security/Claims/ClaimsIdentity.cs,601dacbeca044900
So we don't need to `ToList()` in our code.
=> Remove unnecessary intermediate LINQ execution for claims

src/Microsoft.Azure.SignalR.Emulator/AppBuilderExtensions.cs, src/Microsoft.Azure.SignalR.Emulator/Common/HttpContextExtenstions.cs
Fix https://github.com/Azure/azure-functions-signalrservice-extension/issues/259
Root Cause
============
The latest function extension updated to set userId to an Azure SignalR specific claim type. The emulator needs to be updated accordingly to support such change.
=> Update emulator to support Azure SignalR specific userId

samples/ChatSample/ChatSample.NetCore31/Hub/Chat.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, src/Microsoft.Azure.SignalR.Protocols/ConnectionMessage.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestClientConnectionFactory.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceMessageTests.cs
Fixed 2 bugs
1. The client connection that was migrated to another server will have a rare chance to be closed again.
2. Server sometimes cannot shutdown gracefully after all client connections have been migrated.
Fixed a sample code
#1374
=> Complete both pipe while migrating clients.

src/Microsoft.Azure.SignalR.Common/Exceptions/AzureSignalRUnauthorizedException.cs, src/Microsoft.Azure.SignalR.Common/Exceptions/ExceptionExtensions.cs, src/Microsoft.Azure.SignalR.Common/RestClients/SignalRServiceRestClient.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/Internal/WebSocketsTransport.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerImpl.cs
According to [this](https://docs.microsoft.com/en-us/azure/role-based-access-control/troubleshooting#role-assignment-changes-are-not-being-detected), a role assignments change requires up to 30 minutes to take effect if the token had not been forced refreshed. 
However, it took seldomly longer than 15 minutes in our daily integration tests.
I'd like to try reducing the time to take effect, but now, let's give our customer some hints.
=> Raise user-friendly ex when aad auth failed.

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/Negotiation/RouterWithHealthCheckSwitch.cs, test/Microsoft.Azure.SignalR.Management.Tests/NegotiateProcessorFacts.cs
This affects both persistent mode and transient mode
=> Disable endpoint online check from `IEndpointRouter` side for single endpoint in Serverless SDK

src/Microsoft.Azure.SignalR.AspNet/ServerConnections/ServiceConnectionManager.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionBase.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/RunAzureSignalRTests.cs, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionFacts.cs
Fix `TestRunAzureSignalRWithDefaultRouterNegotiateWithFallback`
Sometimes the test runs too quick, which will cause the `ConnectionInitializedTask` return immediately without service connection even tries to establish.
=> Fix negotiation test

src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/HealthCheckOptions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/RestHealthCheckService.cs, src/Microsoft.Azure.SignalR.Management/IServiceManagerBuilder.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerBuilder.cs, test/Microsoft.Azure.SignalR.Management.Tests/RestHealthCheckServiceFacts.cs
- Fix a bug that health check is not disabled with single endpoint (#1403)
- Deprecate `IServiceManagerBuilder` method (#1406)
=> Merge dev for 1.10.0 fix

src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, test/Microsoft.Azure.SignalR.Management.Tests/DependencyInjectionExtensionFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerOptionsFacts.cs
Users need to use `ServiceManagerOptions.ServiceEndpoints` when they want to use `TokenCrendential`.
Fix problem mentioned at https://github.com/Azure/azure-signalr/issues/1404#issuecomment-908058532
=> Allow transient mode to use `ServiceManagerOptions.ServiceEndpoints`

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR.Management/HubInstanceFactories/ServiceHubLifetimeManagerFactory.cs, src/Microsoft.Azure.SignalR.Management/IServiceHubLifetimeManager`T.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextBuilder.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl`T.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContext`T.cs, src/Microsoft.Azure.SignalR.Management/ServiceManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceManagerImpl.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs
Usage:
```cs
public interface IChatClient
{
Task NewMessage(string message);
}
var typedHubContext = serviceManager.CreateHubContextAsync<IChatClient>(hubName, cancellation);
await typedHubContext.Clients.All.NewMessage("message");
```
=> Support  strong typed hubs in Serverless SDK

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, test/Microsoft.Azure.SignalR.Management.Tests/Negotiation/NegotiationFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/RestHealthCheckServiceFacts.cs
* Add unit tests
Previously `IEndpointRouter` implementation `AutoHealthCheckRouter` is overridden by `DefaultEndpointRouter` introduced by ServerSDK
=> Fix persistent mode still check endpoint health with single endpoint 

Directory.Build.props, build/dependencies.props, src/Directory.Build.props, src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/IConfigurationExtension.cs, test/Microsoft.Azure.SignalR.Common.Tests/Endpoints/IConfigurationExtensionsFacts.cs, test/Microsoft.Azure.SignalR.Common.Tests/Microsoft.Azure.SignalR.Common.Tests.csproj, version.props
- Revert "Add methods to parse `ServiceEndpoint` from configuration based on identity (#1413)"
- Don't roll back the version
=> Revert "Add methods to parse ServiceEndpoint from configuration based on identity (Azure#1413)

src/Microsoft.Azure.SignalR.Management/ServiceHubContext.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, test/Microsoft.Azure.SignalR.Management.Tests/RestHealthCheckServiceFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs
* Make `ServiceHubContext` implements `IDisposable` 
So that we can use `using var serviceHubContext = ...`
* Avoid disposing twice
* Make the class `sealed` to avoid dispose pattern
* Make `Dispose` virtual to allow properly implements dispose pattern in the non-sealed subclass.
Our current sub class is sealed, but in case user want to implement non-sealed subclass.
=> Make `ServiceHubContext` implements `IDisposable`

src/Microsoft.Azure.SignalR.Common/Constants.cs, src/Microsoft.Azure.SignalR.Common/Interfaces/IServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ConnectionFactory.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceMessage.cs, test/Microsoft.Azure.SignalR.AspNet.Tests/ServiceEndpointProviderTests.cs
`ServerId` is required while using our SDK in `server-sticky` mode. 
Well, with aad auth enabled, the server connection will use `AadToken` to connect to our service instead of `AccessToken` signed by our `AccessKey`, which does NOT contain the correct `UserIdentifier`.
To solve this, I'd like to move the `serverId` to the HTTP request header.
=> Send serverId via http header.

src/Microsoft.Azure.SignalR.Common/Utilities/PayloadMessageContent.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ReusableUtf8JsonWriter.cs, test/Microsoft.Azure.SignalR.Common.Tests/Utils/PayloadMessageContentTest.cs
The `Utf8JsonWriter.Reset(Stream)` and  `Utf8JsonWriter.Reset()` don't release the underlying array buffer, which is a memory leak. The problem gets worse with the using of thread-pool. If a `Utf8JsonWriter` is initialized or reset with an `IBufferWriter<byte>`, that won't cause memory leak as the underlying array buffer is null in that case.
* Reset `ReusableUtf8JsonWriter` for persistent mode.
* Optimize: Avoid new a `MediaTypeHeaderValue` every time.
=> Don't reuse `Utf8JsonWriter` for `Stream` output

src/Directory.Build.props
Issue: When AAD auth, we've got an error like this:
>       Failed in authorizing AccessKey for 'https://zityang-signalr-standard-dev-2.service.signalr.net/', will retry in 3 seconds
>      System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
>      File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
>         at Microsoft.Azure.SignalR.AadAccessKey.UpdateAccessKeyAsync()
This error would occur on both server SDK and management SDK. `Microsoft.AspNetCore.Http.Connections.Common` 1.0.0 -> `Newtonsoft.Json` 11.0.2 while other transitive dependencies for `Newtonsoft.Json` are 10.0.*. This causes version …
=> Resolve `Newtonsoft.Json` version conflicts

src/Microsoft.Azure.SignalR.Serverless.Protocols/Microsoft.Azure.SignalR.Serverless.Protocols.csproj
Fix issue that when `IsFinalBuild` == true, the version of serverless protocol project would be the same as other projects.
=> Fix serverless protocol project version

Directory.Build.props, build/dependencies.props, src/Directory.Build.props
Questions: Should we use floating version to get the latest patch version automatically?
* Microsoft.AspNetCore.Http  2.1.0 -> 2.1.22
* Microsof.tAspNetCore.Http.Connections 1.0.0 -> 1.0.15
*  Microsoft.AspNetCore.WebSockets 2.1.0 -> 2.1.7 
* System.Net.WebSockets.WebSocketProtocol 4.5.0 -> 4.5.3
* Microsoft.AspNetCore.Http.Connections.Common 1.0.0 -> 1.0.4
* Microsoft.Extensions.Logging.Abstractions 2.1.0 -> 2.1.1
* Microsoft.AspNetCore.Connections.Abstractions 2.1.0 -> 2.1.2
* Microsoft.Extensions.Primitives 2.1.0 -> 2.1.2
[Use a tool locally](https://docs.opensource.microsoft.com/tools/cg/features/dev/) to running detection like online [Component Governance](https://docs.opensource.microsoft.com/tools/cg/) to get the following report:
<details>
<summary>Scanning report</summary>
[INFO] …
=> Fix security issue from `Microsoft.AspNetCore.SignalR`  1.0.0 version

src/Microsoft.Azure.SignalR.Common/Auth/AuthUtility.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/AuthUtilityTests.cs
KeyId is required to help SignalR Service identity which key should be used to validate the token signature when using AAD.
However, the kid will be the same if you got them with the same Azure Identity (objectId)
In this case, if we enabled the cache, server SDK will get the signature from the cache regardless of the keyValue, while the keys for different endpoints are different though they share the same id.
[code link](https://cs.github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/922901505740480f3fe6349e501ad36082e441e3/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L575)
=> Fix AAD with multiple endpoints

src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs
On .NET standard 2.0, registering multiple hub protocols with the same name is invalid.
https://github.com/aspnet/SignalR/blob/a9def470e3b8e1480c55d1c311e4b37472140307/src/Microsoft.AspNetCore.SignalR.Core/Internal/DefaultHubProtocolResolver.cs#L32
Following task: #1534
=> Fix management SDK error on .NET standard 2.0: Multiple JSON protocols are registered

build/dependencies.props, src/Directory.Build.props
Improve cross-project debug experience. Currently if we want to debug SDK in other projects, we have to reference the local SDK project. With source link or symbol package we don't have to do that.
As the new symbol package format `*.snupkg` is not supported by KoreBuild, we cannot enable symbol package yet.
[Symbol packages](https://docs.microsoft.com/dotnet/standard/library-guidance/nuget#symbol-packages)
[Source link](https://docs.microsoft.com/dotnet/standard/library-guidance/sourcelink)
=> Enable source link and symbol package

src/Microsoft.Azure.SignalR.Management/ServiceManagerImpl.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerFacts.cs
If users want to guarantee message order in persistent mode, they need to set the connection count to 1.
=> Fix bug that Management SDK connection count is fixed to 3

src/Microsoft.Azure.SignalR.Common/Endpoints/EndpointMetrics.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs, src/Microsoft.Azure.SignalR.Common/ServiceMessages/RuntimeServicePingMessages.cs
When using multible endpoint, this metrics will enable customer to route request according to the instance weight.
=> add server connection and connection quota for endpoint metrics

src/Microsoft.Azure.SignalR.AspNet/EndpointProvider/ServiceEndpointProvider.cs, src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/RestClients/RestClientFactory.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, src/Microsoft.Azure.SignalR.Common/Utilities/IsExternalInit.cs, src/Microsoft.Azure.SignalR.Common/Utilities/ParsedConnectionString.cs, src/Microsoft.Azure.SignalR.Management/RestApiProvider.cs, src/Microsoft.Azure.SignalR/EndpointProvider/DefaultServiceEndpointGenerator.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/ConnectionStringParserTests.cs, test/Microsoft.Azure.SignalR.Common.Tests/ServiceEndpointFacts.cs
Users have two ways to set `serverEndpoint`.
* Option 1: in connection string: `serverEndpoint=...`
* Option 2: in the ctor of `ServiceEndpoint`:
```cs
new ServiceEndpoint(new Uri(endpoint), new DefaultAzureCredential())
{
ClientEndpoint = new Uri("https://client-endpoint.com/path"),
ServerEndpoint = new Uri("https://server-endpoint.com/path"),
}
```
Other changes:
* `ServiceEndpoint.AudienceBaseUrl` now ends with slash.
=> Support the customization of endpoint for server to connect to ASRS

.github/workflows/osx.yml
error  : .NET Core 2.0 requires macOS 10.12 or newer. Current version is 11.6.5.
=> Disable osx build due to invalid error

src/Microsoft.Azure.SignalR.Common/Endpoints/ServiceEndpoint.cs, src/Microsoft.Azure.SignalR.Common/Utilities/IsExternalInit.cs
1. Add "serverEndpoint", "clientEndpoint" to constructor parameter. Previously we only have `init` accessor, which is available only since C# 9 and Net Standard 2.0 and .Net Core 3.1 have to specify language version to use the accessor.
2. Make our internal `IsExternalInit` available on .NET 6. Due to unknown reasons, if .NET standard libraries (for example Functions extensions) try to use `init` accessor without our internal `IsExternalInit` class, they will get "set_ServerEndpoint" method not found exception.
=> Fix the "serverEndpoint","clientEndpoint" of `ServiceEndpoint` ctor problem

src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/ConnectionStringParserTests.cs
For historical reasons, we will use `ManagedIdentityCredential` by default when using `type=aad` with no other designated params. It is NOT a best practice with the latest `msal` library anymore.
We added `type=azure` in this PR to change the default behavior, the old `type=aad` will be deprecated and removed in future releases.
=> Add type=azure for connection string.

src/Microsoft.Azure.SignalR.Common/Utilities/ConnectionStringParser.cs, src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.Log.cs, test/Microsoft.Azure.SignalR.Common.Tests/Auth/ConnectionStringParserTests.cs
1. Add `azure`, `azure.msi`, `azure.app` Auth types.
2. Change connection trace log from DEBUG to INFO
=> Release 1.18

src/Microsoft.Azure.SignalR.Serverless.Protocols/Microsoft.Azure.SignalR.Serverless.Protocols.csproj
The next function extensions version is 1.9.0 . Skip 1.8.0 and 1.7.0
=> Update `Serverless.Protocols` version to 1.9.0

src/Microsoft.Azure.SignalR/ApplicationBuilderExtensions.cs, test/Microsoft.Azure.SignalR.E2ETests/SignalR/TestStartup.cs
- Obsolete IApplicationBuilder.UseAzureSignalR. Tell users to use IApplicationBuilder.UseEndpoints
Fixes #1602
=> Obsolete UseAzureSignalR

src/Microsoft.Azure.SignalR/ServerConnections/ServiceConnection.cs
Fixes https://github.com/Azure/azure-signalr/issues/1632
=> When it is NotActive no need to continue processing

src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs
- remove logic for RemoveConnectionFromAllGroups inside the API method `RemoveFromGroupAsync`
- Removed part should be an independent API in the future
=> fix API RemoveFromGroupAsync

build/dependencies.props, src/Microsoft.Azure.SignalR.AspNet/Microsoft.Azure.SignalR.AspNet.csproj, src/Microsoft.Azure.SignalR.Management/Microsoft.Azure.SignalR.Management.csproj, src/Microsoft.Azure.SignalR/Microsoft.Azure.SignalR.csproj, test/Microsoft.Azure.SignalR.AspNet.Tests/Microsoft.Azure.SignalR.AspNet.Tests.csproj
`aspnetcore` releate dependencies are moved to `Common` package, clean up in SignalR/Management side.
=> Clean up dependencies.

src/Microsoft.Azure.SignalR.Management/HubContext/GroupManager.cs, src/Microsoft.Azure.SignalR.Management/HubContext/GroupManagerAdapter.cs, src/Microsoft.Azure.SignalR.Management/IHubLifetimeManager.cs, src/Microsoft.Azure.SignalR.Management/RestHubLifetimeManager.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl.cs, src/Microsoft.Azure.SignalR.Management/ServiceHubContextImpl`T.cs, src/Microsoft.Azure.SignalR.Management/WebsocketsHubLifetimeManager.cs, test/Microsoft.Azure.SignalR.E2ETests/Management/ServiceHubContextE2EFacts.cs
- Separate `RemoveConnectionFromAllGroups` from `RemoveConnectionFromGroup`
- Before this PR, `...FromAllGroups` was implemented by calling `...FromGroup` with `group=null`
=> Fix RemoveConnectionFromAllGroups 

src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs
- payload hu protocol name should ignore case, which consistent to aspnet core signalr
=> fix service protocol

src/Microsoft.Azure.SignalR.AspNet/HubHost/SignalRMessageParser.cs, src/Microsoft.Azure.SignalR.Protocols/ArrayDictionary.cs, src/Microsoft.Azure.SignalR.Protocols/ServiceProtocol.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManagerBase.cs
Perf profiles indicate a significant overhead (both in terms of CPU usage and memory allocation per request) when using relatively heavyweight Dictionary to store message data. Replacing it with ArrayDictionary which is more suitable for keeping a very small number of items in this use case.
=> Use ArrayDictionary to improve perf

docs/swagger/V20220601.json, docs/swagger/V20220601.md
- A swagger generation bug in runtime was fixed. See [here](https://msazure.visualstudio.com/One/_git/OSSServices-SignalR-Service/pullrequest/7767515). 
- All `x-ms-examples` are removed to generate markdown successfully, such as
```
"x-ms-examples": {
"HealthApi_GetServiceStatus": {
"$ref": "./examples/HealthApi_GetServiceStatus.json"
}
}
```
- No change to any other part.
=> Update swagger 20220601

src/Microsoft.Azure.SignalR.Common/ServiceConnections/ServiceConnectionContainerBase.cs
For example, the following scenarios may occasionally fail (due to race condition) without this fix:
- Removing after send should not prevent sending message to group:
~~~
{
await Groups.AddToGroupAsync(connId, group);
await Clients.Group(group).SendAsync(method, msg); // msg may never get delivered to connId
await Groups.RemoveFromGroupAsync(connId, group);
}
~~~
- Messages sent to a group should not get delivered to connections added to group afterwards:
~~~
{
await Groups.RemoveFromGroupAsync(connId, group);
await Clients.Group(group).SendAsync(method, msg); // msg may get sent to connId even though it is only added after SendAsync.
await Groups.AddToGroupAsync(connId, group);
}
~~~
The race conditions affecting the scenarios above are rare and they should work _most of the time_. …
=> Use sticky service connections for ackable messages

samples/ChatSample/ChatSample.NetCore31/Dockerfile
- Refactor for Dockerfile writing best practices
Fixes NONE
Hi!
The Dockerfile placed at "samples/ChatSample/ChatSample.NetCore31/Dockerfile" contains the best practice violation [DL3003](https://github.com/hadolint/hadolint/wiki/DL3003) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3003 occurs if the pattern `RUN cd ...` is used to change directories instead of the dedicated WORKDIR instruction.
This pull request proposes a fix for that smell generated by my fixing tool. The patch was manually verified before opening the pull request. To fix this smell, specifically, the pattern `RUN cd ...` is replaced with the equivalent WORKDIR instruction.
This change is only aimed at fixing that specific smell. If the fix is not valid or useful, please briefly …
=> Fix for Dockerfile smell DL3003

src/Microsoft.Azure.SignalR.Common/Utilities/RestClient.cs, src/Microsoft.Azure.SignalR.Management/Configuration/ServiceManagerOptions.cs, src/Microsoft.Azure.SignalR.Management/DependencyInjectionExtensions.cs, test/Microsoft.Azure.SignalR.Management.Tests/DependencyInjectionExtensionFacts.cs, test/Microsoft.Azure.SignalR.Management.Tests/ServiceManagerOptionsFacts.cs
1. Add `HttpClientTimeout` options
2. Throw `AzureSignalRException` instead of  `AzureSignalRInaccessibleEndpointException` when `HttpRequestException` happens. `HttpRequestException` is a general exception thrown by `HttpClient` or `HttpMessageHandler` and it's not necessarily due to DNS error or incorrect endpoint. Telling the customer to check DNS or endpoint sometimes is misleading.
=> Add HttpClientTimeout options to management SDK

src/Microsoft.Azure.SignalR.Common/Logging/MessageLog.cs, test/Microsoft.Azure.SignalR.Tests/Logging/MessageLogTests.cs
When using log destructuration having logs with {0}, {1} in templates can be an issue as these have different types for each log messages
=> use named templating in log messages

src/Microsoft.Azure.SignalR.Common/Endpoints/AadAccessKey.cs
Current timeout of 10 seconds is insufficient for generating a token and calling the AccessKey endpoint with ServerEndpoint proxy. Running it through Visual Studio, a task cancellation error occurs consistently. To resolve this issue, the timeout has been increased to 100 seconds, which is the default HTTP timeout.
- AuthorizeTimeout has been increased to 100 seconds
Fixes #1802
=> Timeout has been increased to 100 seconds

specs/ClientInvocation.md, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs
Make client invocation supported in sharding mode. Currently CI manager rely on single response from service side which make it not work in multiple endpoints scenarios that server side has to manage all the endpoints results before completion.
=> Partial support client results in sharding mode.

src/Microsoft.Azure.SignalR.Common/Endpoints/EndpointRoutingMode.cs, src/Microsoft.Azure.SignalR/EndpointRouters/DefaultEndpointRouter.cs, src/Microsoft.Azure.SignalR/EndpointRouters/EndpointRouterDecorator.cs, src/Microsoft.Azure.SignalR/ServiceOptions.cs, test/Microsoft.Azure.SignalR.Tests/EndpointRouterTests.cs, test/Microsoft.Azure.SignalR.Tests/MultiEndpointServiceConnectionContainerTests.cs
- Add different endpoint routing mode: `Weighted`, `LeastConnection`, `Random`
- For weighted mode: change the weight definition from _remaining connection quota_ to ( _remaining connection quota / connection capacity)_
=> Support different EndpointRoutingMode

src/Microsoft.Azure.SignalR.Common/ClientInvocation/ICallerClientResultsManager.cs, src/Microsoft.Azure.SignalR.Common/ServiceConnections/MultiEndpointServiceConnectionContainer.cs, src/Microsoft.Azure.SignalR/ClientInvocation/CallerClientResultsManager.cs, src/Microsoft.Azure.SignalR/ClientInvocation/ClientInvocationManager.cs, src/Microsoft.Azure.SignalR/DependencyInjectionExtensions.cs, src/Microsoft.Azure.SignalR/HubHost/ServiceLifetimeManager.cs, test/Microsoft.Azure.SignalR.Tests/ClientInvocationManagerTests.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/DefaultClientInvocationManager.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/ServiceConnectionProxy.cs, test/Microsoft.Azure.SignalR.Tests/Infrastructure/TestOptionsMonitor.cs, test/Microsoft.Azure.SignalR.Tests/ServiceLifetimeManagerFacts.cs
Support client result (also called "client invocation") in sharding mode (multiple endpoints)
Ref: Partial Support PR https://github.com/Azure/azure-signalr/pull/1828
=> Support client results in sharding mode

.github/workflows/osx.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml, build/dependencies.props, src/Microsoft.Azure.SignalR.AspNet/Microsoft.Azure.SignalR.AspNet.csproj, test/Microsoft.Azure.SignalR.Tests/ServiceConnectionTests.cs
Upgrading Microsoft.Owin version to 4.2.2
=> Fix vulnerability
